/* ============================================================
   I18N -- All UI translations EN/JP/KR/VI/ZH
   File: engjap.js
   ============================================================ */

const translations = {
  "en": {
    "home": "Home",
    "language": "Language",
    "settings": "Settings",
    "players": "Players",
    "rounds": "Rounds",
    "summary": "Summary",
    "fontSize": "Font Size",
    "reset": "Reset",
    "resetAll": "Reset App",
    "resetExcept": "Reset Games",
    "enterCourts": "Enter Number of Courts",
    "importPlayers": "Browse Players ▶",
    "gender": "Gender",
    "male": "Male",
    "female": "Female",
    "import": "Import",
    "enterPlayerName": "Enter Player Name",
    "addPlayer2": "Add",
    "fixedPairs2": "Set Fixed Pairs (Optional)",
    "pround": " Round",
    "nround": "Play ",
    "endrounds": "Finish & Next Round ",
    "endSession": "End Session",
    "roundno": "Round ",
    "roundShort": "R",
    "rank": "Rank",
    "name": "Name",
    "wins": "Wins",
    "played": "Played",
    "rested": "Rested",
    "importExample": "Name,Gender\nKari\nBhavani",
    "Timer": "Timer",
    "min": "min",
    "selectPlayer1": "Select Player 1",
    "selectPlayer2": "Select Player 2",
    "small": "Small",
    "medium": "Medium",
    "large": "Large",
    "maxcourts": "Enter Number of Courts",
    "sittingOut": "Resting",
    "courts": "Courts",
    "theme": "Theme",
    "light": "Light",
    "dark": "Dark",
    "export": "Export",
    "exporthtml": "📄 Export Summary",
    "help": "Help",
    "confirmResetAll": "Do you want to reset everything?",
    "confirmResetGames": "Do you want to reset games only?",
    "endRoundsConfirm": "Do you want to end the rounds?",
    "yes": "Yes",
    "browsePlayersSub": "Select from saved players",
    "statusReady": "Status: Ready",
    "statusProgress": "Status: Progress...",
    "minRounds": "Warm-Up Rounds",
    "roundSettings": "Round Settings",
    "competitive": "Competitive",
    "appTitle": "Sports Club Scheduler",
    "tagline": "Badminton & Pickleball",
    "login": "Login",
    "logout": "Logout",
    "createAccount": "Create Account",
    "claimAccount": "Claim Account",
    "email": "Email",
    "password": "Password",
    "confirmPassword": "Confirm Password",
    "newPassword": "New Password",
    "confirmNewPassword": "Confirm New Password",
    "displayName": "Display Name",
    "recoveryKeyword": "Recovery Keyword",
    "forgotPassword": "Forgot password?",
    "resetPassword": "Reset Password",
    "userId": "User ID",
    "nickname": "Nickname",
    "yourEmail": "Your Email",
    "myCard": "My Card",
    "myClubs": "My Clubs",
    "dashboard": "Dashboard",
    "fixedPairs": "Fixed Pairs",
    "selectPlayers": "Select Players",
    "startRounds": "Start Rounds",
    "watchSession": "Watch Session",
    "viewer": "Viewer",
    "organiser": "Organiser",
    "vault": "Vault",
    "chooseMode": "Choose Mode",
    "howUsingApp": "Choose how you are using the app",
    "watchLive": "Watch live rounds & scores",
    "runSession": "Run session, score games, manage players",
    "clubAdmin": "Club admin -- players, requests, management",
    "roundOrganiser": "Round Organiser",
    "vaultManager": "Vault Manager",
    "myClubsTitle": "My Clubs",
    "findClub": "Find a Club",
    "joinClub": "Join",
    "leaveClub": "Leave",
    "noClubSelected": "No club selected",
    "createClub": "Create Club",
    "createNewClub": "Create New Club",
    "createYourClub": "Create Your Club",
    "deleteClub": "Delete Club",
    "connectClub": "Connect",
    "clubManagement": "Club Management",
    "noClubYet": "No club yet -- create one to get started",
    "searchClub": "Search Club",
    "findRequest": "Find & request",
    "submitRequest": "Submit Request",
    "requestSent": "Request sent! Waiting for admin approval.",
    "tapConnect": "Tap to connect",
    "register": "Register",
    "modify": "Modify",
    "requests": "Requests",
    "playing": "Playing",
    "onCourtNow": "on court now",
    "pendingApproval": "pending approval",
    "playersInClub": "players in club",
    "tapToEdit": "tap to edit",
    "joinAClub": "join a club",
    "newClub": "new club",
    "removeClub": "remove club",
    "loadingRequests": "Loading requests...",
    "addPlayer": "Add Player",
    "editPlayer": "Edit Player",
    "addRemove": "Add · Remove",
    "alwaysTogether": "Always together",
    "addAtLeast4": "Add at least 4 players",
    "myProfile": "My Profile",
    "recentMatches": "Recent Matches",
    "sessionStats": "Session stats",
    "sessions": "Sessions",
    "allTimeWins": "All-time Wins",
    "allTimeLosses": "All-time Losses",
    "globalRating": "Global Rating",
    "globalPoints": "Global Points",
    "clubRating": "Club Rating",
    "clubPoints": "Club Points",
    "thisWeek": "This Week",
    "thisMonth": "This Month",
    "thisYear": "This Year",
    "signInStats": "Sign in to view your stats",
    "trackStats": "Track your ratings, wins and match history.",
    "appearance": "Appearance",
    "tileStyle": "Tile Style",
    "flat": "Flat",
    "glow": "Glow",
    "color": "Color",
    "subscription": "Subscription",
    "currentMode": "Current Mode",
    "freeTrial": "🎉 Free Trial",
    "restorePurchase": "Restore Purchase",
    "subscribeNow": "Subscribe Now",
    "trialEnded": "Your free trial has ended",
    "add": "Add",
    "cancel": "Cancel",
    "save": "Save Changes",
    "clear": "Clear",
    "clearHistory": "Clear History",
    "clearFavorites": "Clear Favorites",
    "delete": "Delete",
    "replace": "Replace",
    "skip": "Skip",
    "start": "Start",
    "end": "End",
    "switch": "Switch",
    "change": "Change",
    "info": "Info",
    "preview": "Preview",
    "loading": "Loading...",
    "liveSessions": "Live sessions",
    "liveNow": "Live Now",
    "noLiveSessions": "No live sessions",
    "favourite": "Favourite",
    "history": "History",
    "whoAreYou": "Who are you?",
    "notSelected": "Not selected",
    "getStarted": "Get Started",
    "welcome": "Welcome",
    "selectFromSaved": "Select from saved players",
    "selectNameProfile": "Select your name to personalise your profile",
    "asRegisteredByAdmin": "as registered by admin",
    "givenByAdmin": "given by admin",
    "minSixChars": "min 6 characters",
    "toResetPassword": "to reset password if forgotten",
    "yourNameAlias": "your name or alias",
    "defaultPassword": "Default Password",
    "tile": "Tile",
    "wideTile": "Wide Tile",
    "description": "Description",
    "roundOrganiserDesc": "Run session, score games, manage players",
    "vaultManagerDesc": "Club admin -- players, requests, management",
    "watchLiveDesc": "Watch live rounds & scores",
    "startRoundsBtn": "Start Rounds ›",
    "goBtn": "Go ›",
    "helpGuide": "Help & Guide",
    "findAClub": "Find a Club",
    "addPlayers": "Add Players",
    "player1": "Player 1",
    "player2": "Player 2",
    "editPlayerName": "Edit player name",
    "removePlayer": "Remove player",
    "connectToClub": "Connect to Club",
    "selectClub": "-- Select club --",
    "nextRound": "Next Round",
    "markWinner": "Mark winner",
    "markAllWinners": "Please mark winners for all games",
    "inProgress": "In Progress",
    "lockBtn": "Lock",
    "unlockBtn": "Unlock",
    "playingNow": "Playing Now",
    "registerPlayers": "Register Players",
    "modifyPlayers": "Modify Players",
    "joinRequests": "Join Requests",
    "userID": "User ID",
    "passwordBlank": "Password (leave blank to keep)",
    "selectClubDelete": "-- Select club to delete --",
    "refresh": "↻ Refresh",
    "sync": "↻ Sync",
    "adminBadge": "ADMIN",
    "userBadge": "USER",
    "viewerBadge": "VIEWER",
    "liveBadge": "LIVE",
    "newBadge": "NEW",
    "readyBadge": "READY",
    "welcomeTitle": "Welcome",
    "verifyEmail": "Verify Email",
    "resendCode": "Resend Code",
    "findYourClub": "Find Your Club",
    "resetRoundsOnly": "Reset Rounds Only",
    "resting": "Resting",
    "round": "Round",
    "court": "Court",
    "howUsingAppToday": "How are you using the app today?",
    "claimMyAccount": "Claim My Account",
    "clearBtn": "Clear",
    "clubLabel": "Club",
    "clubRatingLabel": "Club Rating",
    "globalRatingLabel": "Global Rating",
    "clubSchedulerPro": "Club Scheduler Pro",
    "courtsLabel": "Courts",
    "emailLabel": "Email",
    "endBtn": "End",
    "favouriteBtn": "Favourite",
    "joinBtn": "Join",
    "lessOneShuttle": "Less than one shuttle per year",
    "pairsLabel": "Pairs",
    "passwordLabel": "Password",
    "replaceBtn": "Replace",
    "roundsLabel": "Rounds",
    "saveSet": "Save Set",
    "searchByClubName": "Search by club name and request to join",
    "skipBtn": "Skip",
    "startBtn": "Start",
    "switchBtn": "Switch",
    "useAdminMode": "Use Vault mode for full admin access.",
    "selectClubOption": "-- Select club --",
    "loadingClubs": "-- Loading clubs... --",
    "adminAccess": "Admin Access",
    "connectToClubBadminton": "🏸 Connect to Club",
    "browseBtn": "Browse",
    "sessionStatsLabel": "Session stats",
    "summaryLabel": "Summary",
    "subFeature1": "✓ Full stats & session history",
    "subFeature2": "✓ Live rounds & scoring",
    "subFeature3": "✓ Organiser mode -- run sessions",
    "subFeature4": "✓ Players & Fixed Pairs management",
    "subFeature5": "✓ Viewer mode -- watch live scores",
    "backHome": "‹ Home",
    "notConnected": "Not connected",
    "setupBadge": "SETUP",
    "memberMsg": "You are a member of this club.",
    "club": "club",
    "clubs": "clubs",
    "pending": "pending",
    "loginToSeeClubs": "Login to see your clubs",
    "noClubsYetSearch": "No clubs yet. Search below to join one.",
    "noClubsYet": "No clubs yet.",
    "couldNotLoadClubs": "Could not load clubs.",
    "searching": "Searching...",
    "noClubsFoundFor": "No clubs found for",
    "joined": "Joined",
    "welcomeBack": "Welcome back",
    "requestPending": "Request Pending",
    "checking": "Checking...",
    "requestSentTitle": "Request Sent!",
    "waitingAdminApproval": "Waiting for admin approval.",
    "doneBtn": "Done ✓",
    "setUpBtn": "Set Up ›",
    "alreadyTaken": "is already taken in",
    "chooseDifferentNickname": "Choose a different nickname for this club",
    "noRoundsYet": "No rounds yet",
    "joinClubToPlay": "Join a club to view playing players.",
    "noPlayersLocked": "No players currently locked.",
    "failedLoadConnection": "Failed to load. Check connection.",
    "noPlayersInDb": "No players in database yet.",
    "adminAccessRequired": "🔒 Admin access required.",
    "joinClubToManage": "Join a club to manage players.",
    "failedLoadPlayers": "Failed to load players.",
    "noPlayersMatch": "No players match your search.",
    "noClubSelectedJoin": "⚠️ No club selected. Join a club first.",
    "playerNotFound": "Player not found.",
    "noPlayersAvailable": "No players available",
    "pleaseWait": "Please wait...",
    "selectClubTitle": "Select Club",
    "searchFailed": "Search failed. Try again.",
    "noClubsFound": "No clubs found. Check the name.",
    "sendingRequest": "Sending request...",
    "connectClubFirst": "Connect to a club first.",
    "noPendingRequests": "No pending requests.",
    "failedLoadRequests": "Failed to load requests.",
    "forceEndSession": "⏹ Force End Session",
    "ending": "Ending...",
    "typeClubSearch": "Type club name to search...",
    "playerSingular": "player",
    "playerPlural": "players",
    "releaseAll": "🔓 Release All",
    "badgeActive": "Active",
    "badgeMember": "Member",
    "badgePending": "Pending",
    "asNick": "as",
    "requestPendingText": "Request pending",
    "winsShort": "W",
    "lossesShort": "L",
    "sessionActive": "Session Active!",
    "registeredBadge": "✅ registered",
    "noAccountBadge": "no account",
    "genderMale": "Male",
    "genderFemale": "Female",
    "genderAll": "All",
    "searchPlayers": "Search players...",
    "searchPlayerDot": "Search player...",
    "searchHelp": "Search help...",
    "noResultsFound": "No results found",
    "adminBadgeFull": "🔑 Admin",
    "userBadgeFull": "👤 User",
    "changePassword": "🔑 Change Password",
    "wrongPassword": "Wrong password. Try again.",
    "passwordMin4": "Password must be at least 4 characters.",
    "passwordsNotMatch": "Passwords do not match",
    "passwordMin6": "Password must be at least 6 characters",
    "memberAdminDiff": "Member and admin passwords must be different.",
    "emailRequired": "Email is required",
    "emailInvalid": "Please enter a valid email",
    "displayNameMin2": "Display name must be at least 2 characters",
    "recoveryMin3": "Recovery keyword must be at least 3 characters",
    "emailAlreadyReg": "Email already registered. Please login.",
    "signupFailed": "Sign up failed. Please try again.",
    "enterEmail": "Please enter your email",
    "enterPassword": "Please enter your password",
    "noAccountEmail": "No account found with this email",
    "wrongPasswordLogin": "Wrong password",
    "loginFailed": "Login failed. Please try again.",
    "enterRecovery": "Please enter your recovery keyword",
    "emailRecoveryWrong": "Email or recovery keyword is incorrect",
    "resetFailed": "Reset failed. Please try again.",
    "nicknameNotFound": "Nickname not found in this club. Check with your admin.",
    "alreadyClaimed": "This account has already been claimed. Please login or use Forgot Password.",
    "defaultPwWrong": "Default password is incorrect. Check with your admin.",
    "emailAlreadyUsed": "This email is already registered. Use a different email.",
    "nameCannotBeEmpty": "Name cannot be empty.",
    "saving": "Saving...",
    "saved": "✅ Saved!",
    "enterClubName": "Enter club name.",
    "enterMemberPw": "Enter member password.",
    "enterAdminPw": "Enter admin password.",
    "selectPlayersStep": "Select Players",
    "addAtLeast4Step": "Add at least 4 players to begin",
    "fixedPairsStep": "Fixed Pairs",
    "fixedPairsOptional": "Optional -- pair players who always play together",
    "skippedOptional": "Skipped (optional)",
    "courtSettings": "Court Settings",
    "setCourtMode": "Set courts and play mode",
    "randomMode": "Random",
    "startRoundsStep": "Start Rounds",
    "allSetReady": "All set -- ready to play!",
    "sessionInProgress": "Session in progress",
    "optional": "Optional",
    "liveSession": "live session",
    "youMemberMultipleClubs": "You are a member of multiple clubs",
    "requestToJoin": "Request to Join ›",
    "accept": "✓ Accept",
    "reject": "✗ Reject",
    "verifyEmailTitle": "Verify Email",
    "enterSixDigit": "Enter the 6-digit code sent to",
    "verifyBtn": "Verify",
    "enterSixDigitHint": "Enter 6-digit code",
    "codeResent": "✅ Code resent",
    "passwordReset": "✅ Password reset! Please login.",
    "noClubsFoundDot": "No clubs found.",
    "couldNotLoadClubsErr": "❌ Could not load clubs:",
    "pleaseSelectClub": "Please select a club.",
    "enterPasswordHint": "Enter password.",
    "enterMemberPwHint": "Enter member password.",
    "wrongPasswordHint": "Wrong password.",
    "joinedSuccessfully": "✅ Joined successfully",
    "connectedAsMember": "✅ Connected as Member",
    "noSessionData": "No session data yet.<br>Complete some rounds first.",
    "noSessionDataAvail": "No session data available.",
    "couldNotLoadSession": "Could not load session data.",
    "today": "Today",
    "yesterday": "Yesterday",
    "forceEndConfirm": "Force end this session? This cannot be undone.",
    "rookie": "Rookie",
    "clubLevel": "Club",
    "competitiveLevel": "Competitive",
    "advancedLevel": "Advanced",
    "eliteLevel": "Elite",
    "notSelectedProfile": "Not selected",
    "loadingPlayers": "Loading players...",
    "noPlayersInClub": "No players found in your club.",
    "pinMustBe4": "PIN must be exactly 4 digits.",
    "pinsNotMatch": "PINs do not match.",
    "recoveryTooShort": "Recovery word too short.",
    "savingPin": "⏳ Saving...",
    "failedSave": "Failed to save. Try again.",
    "playerNotFoundPin": "Player not found.",
    "wrongPin": "❌ Wrong PIN. Try again.",
    "wrongRecovery": "❌ Wrong recovery word.",
    "pinMust4": "PIN must be 4 digits.",
    "subscribedPro": "✅ Subscribed! Welcome to Pro.",
    "purchaseCancelled": "Purchase cancelled.",
    "billingAppOnly": "Billing only available in the app.",
    "purchaseRestored": "✅ Purchase restored!",
    "noActiveSubscription": "No active subscription found.",
    "couldNotRestore": "Could not restore purchases.",
    "daysRemaining": "days remaining",
    "trialEndedSub": "🔒 Trial Ended",
    "subscribeToContInue": "Subscribe to continue",
    "activeSubscription": "✅ Active",
    "subscribed": "Subscribed",
    "noRegisteredPlayers": "No registered players found",
    "clearHistoryConfirm": "Clear history?",
    "clearFavoritesConfirm": "Clear favorites?",
    "helpUnavailable": "Help unavailable. Check your connection.",
    "stillNeedHelp": "Still need help? Contact support",
    "syncing": "🔄 Syncing...",
    "noClubSelectedWarn": "⚠️ No club selected",
    "noPlayersFoundWarn": "⚠️ No players found",
    "offlineCache": "⚠️ Offline -- using cache",
    "welcomeToApp": "Welcome to Sports Club Scheduler",
    "connectClubToStart": "Connect to your club to get started.",
    "goToVault": "Go to Vault",
    "startGame": "Start",
    "readyGame": "Ready",
    "inProgressGame": "In Progress",
    "noneGame": "None",
    "emptyGame": "(Empty)",
    "releaseFromSession": "from active session?",
    "releaseAllConfirm": "Release ALL locked players?",
    "adminRole": "· Admin",
    "userRole": "· User",
    "leaveClubConfirm": "Leave this club?",
    "leaveVaultConfirm": "Leave this club? You will need to reconnect to access Vault.",
    "awaitingApproval": "is awaiting admin approval. Check back soon.",
    "yourRequestToJoin": "Your request to join",
    "notAvailable": "Not available",
    "creatingClub": "Creating...",
    "creatingClubDot": "Creating club...",
    "selectClubToDelete": "Select a club to delete.",
    "verifyingDot": "Verifying...",
    "clubNotFound": "Club not found.",
    "wrongAdminPassword": "Wrong admin password.",
    "playerNicknamePh": "Player nickname",
    "defaultPasswordPh": "e.g. club123",
    "enterDefaultPwAll": "Please enter a default password for all players.",
    "registeringDot": "Registering...",
    "enterNickname": "Please enter a nickname.",
    "enterDefaultPw": "Please set a default password.",
    "nicknameExists": "Nickname already exists in this club.",
    "passwordsNotMatchDot": "Passwords do not match.",
    "justStarted": "just started",
    "selectYourClub": "Select your club",
    "enterYourNickname": "Enter your nickname",
    "enterDefaultPassword": "Enter default password",
    "sendingVerification": "Sending verification code...",
    "claimFailed": "Claim failed. Please try again.",
    "invalidOTP": "Invalid OTP",
    "otpExpired": "OTP expired. Please request a new one.",
    "accountNotFound": "Account not found",
    "pleaseLoginFirst": "Please login first",
    "invalidInviteCode": "Invalid invite code. Check with your organiser.",
    "failedToJoinClub": "Failed to join club.",
    "searchFailed2": "Search failed",
    "provideNickname": "Please provide a nickname.",
    "failedSendRequest": "Failed to send request",
    "failedLoadRequests2": "Failed to load requests",
    "failedAcceptRequest": "Failed to accept request",
    "failedRejectRequest": "Failed to reject request",
    "pleaseSelectClubDot": "Please select a club.",
    "enterClubPassword": "Enter the club password.",
    "checkingDot": "Checking...",
    "wrongPasswordDot": "Wrong password.",
    "joinedAsAdmin": "✅ Joined as Admin",
    "enterAdminPasswordPh": "Admin password",
    "enterAdminPasswordHint": "Enter the admin password",
    "checkingDotDot": "Checking...",
    "wrongAdminPw": "Wrong admin password",
    "endingSession": "⏹ Ending session...",
    "sessionEnded": "✅ Session ended",
    "clubCreatedAdmin": "created! You are now Admin.",
    "setPinTitle": "Set PIN (4 digits)",
    "confirmPin": "Confirm PIN",
    "recoveryWordSecret": "Recovery word (secret)",
    "enterPin": "Enter PIN",
    "recoveryWord": "Recovery word",
    "newPin": "New PIN (4 digits)",
    "confirmNewPin": "Confirm new PIN",
    "alreadyPlayingSession": "Already playing in another session",
    "availableStatus": "Available",
    "searchToAddPlayer": "Search to add player...",
    "tapToToggleGender": "Tap to toggle gender",
    "startingRating": "Starting rating",
    "removeBtn": "Remove",
    "alreadyExists": "already exists",
    "currentlyPlayingSession": "Currently playing in another session",
    "liveNowTitle": "Live Now",
    "recentSessions": "Recent Sessions",
    "noActiveSessions": "No active sessions right now",
    "noRecentSessions": "No recent sessions found",
    "playersCount": "players",
    "roundsCount": "rounds",
    "setupProfileFirst": "Set up your profile first.",
    "tapProfileIcon": "Tap the profile icon to select your name.",
    "noClubSelectedDash": "No club selected.",
    "goToClubTab": "Go to Club tab to join a club.",
    "couldNotLoadSessions": "Could not load sessions.",
    "checkConnection": "Check your connection.",
    "retryBtn": "↺ Retry",
    "pendingPrefix": "⏳ Pending: ",
    "deleteSetConfirm": "Delete set",
    "noClubSelectedWarn2": "⚠️ No club selected.",
    "adminModeRequired": "⚠️ Admin mode required.",
    "noPlayersYetVault": "Your club has no players yet. Add players in the Vault to get started.",
    "clubPasswordPh": "Club password",
    "clubNamePh": "Club name",
    "memberPasswordPh": "Member password",
    "errorPrefix": "Error: ",
    "playerPrefix": "Player ",
    "sessionBadge": "SESSION",
    "vsLabel": "VS",
    "playersSelected": "selected",
    "playersActive": "active",
    "pairSet": "pair set",
    "pairsSet": "pairs set",
    "courtSingle": "court",
    "courtPlural": "courts",
    "report": "Report",
    "monthlyStats": "monthly stats",
    "foundInClub": "found in",
    "enterDefaultPwClaim": "Enter your default password to join:",
    "claimAndJoin": "Claim & Join",
    "historyBtn": "History"
  },
  "jp": {
    "home": "ホーム",
    "players": "選手一覧",
    "rounds": "試合ラウンド",
    "summary": "集計",
    "language": "言語",
    "fontSize": "文字サイズ",
    "reset": "リセット",
    "resetAll": "全てをリセット",
    "resetExcept": "プレーヤー以外をリセット",
    "enterCourts": "コート数を入力",
    "importPlayers": "プレイヤーを閲覧 ▶",
    "gender": "性別",
    "male": "男",
    "female": "女",
    "import": "取り込み",
    "enterPlayerName": "選手名を入力",
    "fixedPairs2": "固定ペア設定（任意）",
    "pround": " ラウンド",
    "nround": "ラウンド開始 ",
    "endrounds": "終了して次のラウンド ",
    "endSession": "セッション終了",
    "roundno": "ラウンド ",
    "roundShort": "R",
    "rank": "順位",
    "name": "名前",
    "wins": "勝利",
    "played": "試合数",
    "rested": "休憩数",
    "importExample": "名前,性別\nカリ\nババニ",
    "Timer": "タイマー",
    "min": "分",
    "selectPlayer1": "プレーヤー1を選択",
    "selectPlayer2": "プレーヤー2を選択",
    "small": "小",
    "medium": "中",
    "large": "大",
    "maxcourts": "コートの数を入力してください",
    "sittingOut": "休憩中:",
    "courts": "コート",
    "theme": "テーマ",
    "light": "ライト",
    "dark": "ダーク",
    "export": "エクスポート",
    "exporthtml": "📄 概要出力",
    "confirmResetAll": "すべてをリセットしますか？",
    "confirmResetGames": "試合のみをリセットしますか？",
    "endRoundsConfirm": "ラウンドを終了しますか？",
    "yes": "はい",
    "help": "ヘルプ",
    "statusReady": "状態: 準備完了",
    "statusProgress": "状態: 進行中...",
    "minRounds": "ウォームアップラウンド",
    "roundSettings": "ラウンド設定",
    "competitive": "競技モード",
    "browsePlayersSub": "保存済みプレイヤーから選択",
    "appTitle": "スポーツクラブスケジューラー",
    "tagline": "バドミントン＆ピックルボール",
    "login": "ログイン",
    "logout": "ログアウト",
    "createAccount": "アカウント作成",
    "claimAccount": "アカウント申請",
    "email": "メール",
    "password": "パスワード",
    "confirmPassword": "パスワード確認",
    "newPassword": "新しいパスワード",
    "confirmNewPassword": "新しいパスワード確認",
    "displayName": "表示名",
    "recoveryKeyword": "回復キーワード",
    "forgotPassword": "パスワードを忘れた方",
    "resetPassword": "パスワードリセット",
    "userId": "ユーザーID",
    "nickname": "ニックネーム",
    "yourEmail": "あなたのメール",
    "myCard": "マイカード",
    "myClubs": "マイクラブ",
    "dashboard": "ダッシュボード",
    "fixedPairs": "固定ペア",
    "selectPlayers": "選手を選択",
    "startRounds": "ラウンド開始",
    "watchSession": "セッション観戦",
    "viewer": "観戦者",
    "organiser": "オーガナイザー",
    "vault": "ヴォールト",
    "chooseMode": "モードを選択",
    "howUsingApp": "アプリの使い方を選択してください",
    "watchLive": "ライブラウンド＆スコアを観戦",
    "runSession": "セッション運営・スコア管理・選手管理",
    "clubAdmin": "クラブ管理・選手・リクエスト",
    "roundOrganiser": "ラウンドオーガナイザー",
    "vaultManager": "ヴォールトマネージャー",
    "myClubsTitle": "マイクラブ",
    "findClub": "クラブを検索",
    "joinClub": "参加",
    "leaveClub": "退会",
    "noClubSelected": "クラブ未選択",
    "createClub": "クラブ作成",
    "createNewClub": "新しいクラブを作成",
    "createYourClub": "クラブを作成する",
    "deleteClub": "クラブ削除",
    "connectClub": "接続",
    "clubManagement": "クラブ管理",
    "noClubYet": "クラブがありません。作成してください",
    "searchClub": "クラブ検索",
    "findRequest": "検索・申請",
    "submitRequest": "申請を送信",
    "requestSent": "申請を送信しました。管理者の承認をお待ちください。",
    "tapConnect": "タップして接続",
    "register": "登録",
    "modify": "変更",
    "requests": "リクエスト",
    "playing": "試合中",
    "onCourtNow": "現在試合中",
    "pendingApproval": "承認待ち",
    "playersInClub": "クラブ内選手",
    "tapToEdit": "タップして編集",
    "joinAClub": "クラブに参加",
    "newClub": "新しいクラブ",
    "removeClub": "クラブを削除",
    "loadingRequests": "リクエストを読み込み中...",
    "addPlayer": "選手を追加",
    "editPlayer": "選手を編集",
    "addRemove": "追加・削除",
    "alwaysTogether": "常にペア",
    "addAtLeast4": "4人以上追加してください",
    "myProfile": "マイプロフィール",
    "recentMatches": "最近の試合",
    "sessionStats": "セッション統計",
    "sessions": "セッション",
    "allTimeWins": "総勝利数",
    "allTimeLosses": "総敗北数",
    "globalRating": "グローバルレーティング",
    "globalPoints": "グローバルポイント",
    "clubRating": "クラブレーティング",
    "clubPoints": "クラブポイント",
    "thisWeek": "今週",
    "thisMonth": "今月",
    "thisYear": "今年",
    "signInStats": "統計を見るにはサインインしてください",
    "trackStats": "レーティング・勝利・試合履歴を追跡",
    "appearance": "外観",
    "tileStyle": "タイルスタイル",
    "flat": "フラット",
    "glow": "グロー",
    "color": "カラー",
    "subscription": "サブスクリプション",
    "currentMode": "現在のモード",
    "freeTrial": "🎉 無料トライアル",
    "restorePurchase": "購入を復元",
    "subscribeNow": "今すぐ購読",
    "trialEnded": "無料トライアルが終了しました",
    "add": "追加",
    "cancel": "キャンセル",
    "save": "変更を保存",
    "clear": "クリア",
    "clearHistory": "履歴をクリア",
    "clearFavorites": "お気に入りをクリア",
    "delete": "削除",
    "replace": "置換",
    "skip": "スキップ",
    "start": "開始",
    "end": "終了",
    "switch": "切替",
    "change": "変更",
    "info": "情報",
    "preview": "プレビュー",
    "loading": "読み込み中...",
    "liveSessions": "ライブセッション",
    "liveNow": "現在ライブ中",
    "noLiveSessions": "ライブセッションなし",
    "favourite": "お気に入り",
    "history": "履歴",
    "whoAreYou": "あなたは誰ですか？",
    "notSelected": "未選択",
    "getStarted": "始める",
    "welcome": "ようこそ",
    "selectFromSaved": "保存済みから選択",
    "selectNameProfile": "プロフィール設定のために名前を選択",
    "asRegisteredByAdmin": "管理者が登録した名前",
    "givenByAdmin": "管理者から提供",
    "minSixChars": "6文字以上",
    "toResetPassword": "パスワードリセット用",
    "yourNameAlias": "あなたの名前またはニックネーム",
    "defaultPassword": "デフォルトパスワード",
    "tile": "タイル",
    "wideTile": "ワイドタイル",
    "description": "説明",
    "addPlayer2": "追加",
    "addPlayers": "選手を追加",
    "adminAccess": "管理者アクセス",
    "adminBadge": "ADMIN",
    "backHome": "‹ ホーム",
    "browseBtn": "参照",
    "claimMyAccount": "アカウントを申請",
    "clearBtn": "クリア",
    "clubLabel": "クラブ",
    "clubRatingLabel": "クラブレーティング",
    "clubSchedulerPro": "CLUB Scheduler Pro",
    "connectToClub": "クラブに接続",
    "connectToClubBadminton": "🏸 クラブに接続",
    "court": "コート",
    "courtsLabel": "コート",
    "editPlayerName": "選手名を編集",
    "emailLabel": "メール",
    "endBtn": "終了",
    "favouriteBtn": "お気に入り",
    "findAClub": "クラブを探す",
    "findYourClub": "クラブを見つける",
    "globalRatingLabel": "グローバルレーティング",
    "goBtn": "開始 ›",
    "helpGuide": "ヘルプ＆ガイド",
    "howUsingAppToday": "今日はどのようにアプリを使用しますか？",
    "inProgress": "進行中",
    "joinBtn": "参加",
    "joinRequests": "参加リクエスト",
    "lessOneShuttle": "年間シャトル1個未満",
    "liveBadge": "LIVE",
    "loadingClubs": "-- クラブを読み込み中... --",
    "lockBtn": "ロック",
    "markAllWinners": "全試合の勝者をマークしてください",
    "markWinner": "勝者をマーク",
    "modifyPlayers": "選手を変更",
    "newBadge": "NEW",
    "nextRound": "次のラウンド",
    "pairsLabel": "ペア",
    "passwordBlank": "パスワード（変更しない場合は空白）",
    "passwordLabel": "パスワード",
    "player1": "プレーヤー1",
    "player2": "プレーヤー2",
    "playingNow": "現在試合中",
    "readyBadge": "READY",
    "refresh": "↻ 更新",
    "registerPlayers": "選手を登録",
    "removePlayer": "選手を削除",
    "replaceBtn": "置換",
    "resendCode": "コードを再送信",
    "resetRoundsOnly": "ラウンドのみリセット",
    "resting": "休憩中",
    "round": "ラウンド",
    "roundOrganiserDesc": "セッション運営・スコア管理・選手管理",
    "roundsLabel": "ラウンド",
    "saveSet": "セットを保存",
    "searchByClubName": "クラブ名で検索してリクエスト",
    "selectClub": "-- クラブを選択 --",
    "selectClubDelete": "-- 削除するクラブを選択 --",
    "selectClubOption": "-- クラブを選択 --",
    "sessionStatsLabel": "セッション統計",
    "settings": "設定",
    "skipBtn": "スキップ",
    "startBtn": "開始",
    "startRoundsBtn": "ラウンド開始 ›",
    "subFeature1": "✓ 完全な統計とセッション履歴",
    "subFeature2": "✓ ライブラウンドとスコアリング",
    "subFeature3": "✓ オーガナイザーモード -- セッション運営",
    "subFeature4": "✓ 選手と固定ペア管理",
    "subFeature5": "✓ 観戦者モード -- ライブスコア観戦",
    "summaryLabel": "集計",
    "switchBtn": "切替",
    "sync": "↻ 同期",
    "unlockBtn": "ロック解除",
    "useAdminMode": "Vaultモードで完全な管理アクセスを利用",
    "userBadge": "USER",
    "userID": "ユーザーID",
    "vaultManagerDesc": "クラブ管理・選手・リクエスト",
    "verifyEmail": "メールを認証",
    "viewerBadge": "VIEWER",
    "watchLiveDesc": "ライブラウンド＆スコアを観戦",
    "welcomeTitle": "ようこそ",
    "notConnected": "未接続",
    "setupBadge": "SETUP",
    "memberMsg": "このクラブのメンバーです。",
    "club": "クラブ",
    "clubs": "クラブ",
    "pending": "保留中",
    "loginToSeeClubs": "クラブを表示するにはログインしてください",
    "noClubsYetSearch": "クラブがありません。下で検索して参加してください。",
    "noClubsYet": "クラブがありません。",
    "couldNotLoadClubs": "クラブを読み込めませんでした。",
    "searching": "検索中...",
    "noClubsFoundFor": "見つかりませんでした",
    "joined": "参加済み",
    "welcomeBack": "おかえりなさい",
    "requestPending": "リクエスト保留中",
    "checking": "確認中...",
    "requestSentTitle": "リクエスト送信完了！",
    "waitingAdminApproval": "管理者の承認をお待ちください。",
    "doneBtn": "完了 ✓",
    "setUpBtn": "設定 ›",
    "alreadyTaken": "は既に使用されています",
    "chooseDifferentNickname": "このクラブで別のニックネームを選択してください",
    "noRoundsYet": "ラウンドがありません",
    "joinClubToPlay": "プレー中の選手を表示するにはクラブに参加してください。",
    "noPlayersLocked": "現在ロックされている選手はいません。",
    "failedLoadConnection": "読み込みに失敗しました。接続を確認してください。",
    "noPlayersInDb": "まだ選手がいません。",
    "adminAccessRequired": "🔒 管理者アクセスが必要です。",
    "joinClubToManage": "選手を管理するにはクラブに参加してください。",
    "failedLoadPlayers": "選手の読み込みに失敗しました。",
    "noPlayersMatch": "検索条件に一致する選手がいません。",
    "noClubSelectedJoin": "⚠️ クラブが選択されていません。まずクラブに参加してください。",
    "playerNotFound": "選手が見つかりません。",
    "noPlayersAvailable": "利用可能な選手がいません",
    "pleaseWait": "しばらくお待ちください...",
    "selectClubTitle": "クラブを選択",
    "searchFailed": "検索に失敗しました。もう一度試してください。",
    "noClubsFound": "クラブが見つかりません。名前を確認してください。",
    "sendingRequest": "リクエスト送信中...",
    "connectClubFirst": "先にクラブに接続してください。",
    "noPendingRequests": "保留中のリクエストはありません。",
    "failedLoadRequests": "リクエストの読み込みに失敗しました。",
    "forceEndSession": "⏹ セッションを強制終了",
    "ending": "終了中...",
    "typeClubSearch": "クラブ名を入力して検索...",
    "playerSingular": "選手",
    "playerPlural": "選手",
    "releaseAll": "🔓 全員解放",
    "badgeActive": "アクティブ",
    "badgeMember": "メンバー",
    "badgePending": "保留中",
    "asNick": "として",
    "requestPendingText": "リクエスト保留中",
    "winsShort": "勝",
    "lossesShort": "負",
    "sessionActive": "セッション開始！",
    "registeredBadge": "✅ 登録済み",
    "noAccountBadge": "アカウントなし",
    "genderMale": "男性",
    "genderFemale": "女性",
    "genderAll": "全て",
    "searchPlayers": "選手を検索...",
    "searchPlayerDot": "選手を検索...",
    "searchHelp": "ヘルプを検索...",
    "noResultsFound": "結果が見つかりません",
    "adminBadgeFull": "🔑 管理者",
    "userBadgeFull": "👤 ユーザー",
    "changePassword": "🔑 パスワード変更",
    "wrongPassword": "パスワードが違います。再試行してください。",
    "passwordMin4": "パスワードは4文字以上必要です。",
    "passwordsNotMatch": "パスワードが一致しません",
    "passwordMin6": "パスワードは6文字以上必要です",
    "memberAdminDiff": "メンバーと管理者のパスワードは異なる必要があります。",
    "emailRequired": "メールアドレスは必須です",
    "emailInvalid": "有効なメールアドレスを入力してください",
    "displayNameMin2": "表示名は2文字以上必要です",
    "recoveryMin3": "回復キーワードは3文字以上必要です",
    "emailAlreadyReg": "このメールは既に登録されています。ログインしてください。",
    "signupFailed": "登録に失敗しました。再試行してください。",
    "enterEmail": "メールアドレスを入力してください",
    "enterPassword": "パスワードを入力してください",
    "noAccountEmail": "このメールのアカウントが見つかりません",
    "wrongPasswordLogin": "パスワードが違います",
    "loginFailed": "ログインに失敗しました。再試行してください。",
    "enterRecovery": "回復キーワードを入力してください",
    "emailRecoveryWrong": "メールまたは回復キーワードが正しくありません",
    "resetFailed": "リセットに失敗しました。再試行してください。",
    "nicknameNotFound": "このクラブにニックネームが見つかりません。管理者に確認してください。",
    "alreadyClaimed": "このアカウントは既に申請済みです。ログインするかパスワードをリセットしてください。",
    "defaultPwWrong": "デフォルトパスワードが違います。管理者に確認してください。",
    "emailAlreadyUsed": "このメールは既に登録されています。別のメールを使用してください。",
    "nameCannotBeEmpty": "名前は空にできません。",
    "saving": "保存中...",
    "saved": "✅ 保存しました！",
    "enterClubName": "クラブ名を入力してください。",
    "enterMemberPw": "メンバーパスワードを入力してください。",
    "enterAdminPw": "管理者パスワードを入力してください。",
    "selectPlayersStep": "選手を選択",
    "addAtLeast4Step": "開始するには4人以上の選手を追加してください",
    "fixedPairsStep": "固定ペア",
    "fixedPairsOptional": "任意 -- 常に一緒にプレーする選手をペアにする",
    "skippedOptional": "スキップ（任意）",
    "courtSettings": "コート設定",
    "setCourtMode": "コートとプレーモードを設定",
    "randomMode": "ランダム",
    "startRoundsStep": "ラウンド開始",
    "allSetReady": "準備完了 -- プレー開始！",
    "sessionInProgress": "セッション進行中",
    "optional": "任意",
    "liveSession": "ライブセッション",
    "youMemberMultipleClubs": "複数のクラブのメンバーです",
    "requestToJoin": "参加リクエスト ›",
    "accept": "✓ 承認",
    "reject": "✗ 拒否",
    "verifyEmailTitle": "メール認証",
    "enterSixDigit": "送信された6桁のコードを入力",
    "verifyBtn": "認証",
    "enterSixDigitHint": "6桁のコードを入力",
    "codeResent": "✅ コードを再送信しました",
    "passwordReset": "✅ パスワードをリセットしました！ログインしてください。",
    "noClubsFoundDot": "クラブが見つかりません。",
    "couldNotLoadClubsErr": "❌ クラブを読み込めませんでした:",
    "pleaseSelectClub": "クラブを選択してください。",
    "enterPasswordHint": "パスワードを入力。",
    "enterMemberPwHint": "メンバーパスワードを入力。",
    "wrongPasswordHint": "パスワードが違います。",
    "joinedSuccessfully": "✅ 参加しました",
    "connectedAsMember": "✅ メンバーとして接続しました",
    "noSessionData": "セッションデータがありません。<br>まずラウンドを完了してください。",
    "noSessionDataAvail": "セッションデータがありません。",
    "couldNotLoadSession": "セッションデータを読み込めませんでした。",
    "today": "今日",
    "yesterday": "昨日",
    "forceEndConfirm": "このセッションを強制終了しますか？この操作は取り消せません。",
    "rookie": "初心者",
    "clubLevel": "クラブ",
    "competitiveLevel": "競技",
    "advancedLevel": "上級",
    "eliteLevel": "エリート",
    "notSelectedProfile": "未選択",
    "loadingPlayers": "選手を読み込み中...",
    "noPlayersInClub": "クラブに選手が見つかりません。",
    "pinMustBe4": "PINは正確に4桁である必要があります。",
    "pinsNotMatch": "PINが一致しません。",
    "recoveryTooShort": "回復キーワードが短すぎます。",
    "savingPin": "⏳ 保存中...",
    "failedSave": "保存に失敗しました。再試行してください。",
    "playerNotFoundPin": "選手が見つかりません。",
    "wrongPin": "❌ PINが違います。再試行してください。",
    "wrongRecovery": "❌ 回復キーワードが違います。",
    "pinMust4": "PINは4桁である必要があります。",
    "subscribedPro": "✅ 登録完了！Proへようこそ。",
    "purchaseCancelled": "購入がキャンセルされました。",
    "billingAppOnly": "課金はアプリ内でのみ利用できます。",
    "purchaseRestored": "✅ 購入を復元しました！",
    "noActiveSubscription": "有効なサブスクリプションが見つかりません。",
    "couldNotRestore": "購入を復元できませんでした。",
    "daysRemaining": "日残り",
    "trialEndedSub": "🔒 トライアル終了",
    "subscribeToContInue": "続けるには購読してください",
    "activeSubscription": "✅ アクティブ",
    "subscribed": "購読中",
    "noRegisteredPlayers": "登録済み選手が見つかりません",
    "clearHistoryConfirm": "履歴をクリアしますか？",
    "clearFavoritesConfirm": "お気に入りをクリアしますか？",
    "helpUnavailable": "ヘルプを利用できません。接続を確認してください。",
    "stillNeedHelp": "まだ助けが必要ですか？サポートにお問い合わせください",
    "syncing": "🔄 同期中...",
    "noClubSelectedWarn": "⚠️ クラブが選択されていません",
    "noPlayersFoundWarn": "⚠️ 選手が見つかりません",
    "offlineCache": "⚠️ オフライン -- キャッシュを使用",
    "welcomeToApp": "スポーツクラブスケジューラーへようこそ",
    "connectClubToStart": "クラブに接続して始めましょう。",
    "goToVault": "Vaultへ",
    "startGame": "開始",
    "readyGame": "準備完了",
    "inProgressGame": "進行中",
    "noneGame": "なし",
    "emptyGame": "（空）",
    "releaseFromSession": "アクティブセッションから？",
    "releaseAllConfirm": "全ての選手のロックを解除しますか？",
    "adminRole": "· 管理者",
    "userRole": "· ユーザー",
    "leaveClubConfirm": "このクラブを退会しますか？",
    "leaveVaultConfirm": "このクラブを退会しますか？Vaultへのアクセスには再接続が必要です。",
    "awaitingApproval": "の管理者承認を待っています。後で確認してください。",
    "yourRequestToJoin": "参加リクエスト：",
    "notAvailable": "利用不可",
    "creatingClub": "作成中...",
    "creatingClubDot": "クラブを作成中...",
    "selectClubToDelete": "削除するクラブを選択してください。",
    "verifyingDot": "確認中...",
    "clubNotFound": "クラブが見つかりません。",
    "wrongAdminPassword": "管理者パスワードが違います。",
    "playerNicknamePh": "選手のニックネーム",
    "defaultPasswordPh": "例：club123",
    "enterDefaultPwAll": "全選手のデフォルトパスワードを入力してください。",
    "registeringDot": "登録中...",
    "enterNickname": "ニックネームを入力してください。",
    "enterDefaultPw": "デフォルトパスワードを設定してください。",
    "nicknameExists": "このクラブにニックネームが既に存在します。",
    "passwordsNotMatchDot": "パスワードが一致しません。",
    "justStarted": "開始したばかり",
    "selectYourClub": "クラブを選択してください",
    "enterYourNickname": "ニックネームを入力してください",
    "enterDefaultPassword": "デフォルトパスワードを入力",
    "sendingVerification": "認証コードを送信中...",
    "claimFailed": "申請に失敗しました。再試行してください。",
    "invalidOTP": "無効なOTP",
    "otpExpired": "OTPの有効期限が切れました。新しいものをリクエストしてください。",
    "accountNotFound": "アカウントが見つかりません",
    "pleaseLoginFirst": "まずログインしてください",
    "invalidInviteCode": "無効な招待コードです。オーガナイザーに確認してください。",
    "failedToJoinClub": "クラブへの参加に失敗しました。",
    "searchFailed2": "検索に失敗しました",
    "provideNickname": "ニックネームを入力してください。",
    "failedSendRequest": "リクエストの送信に失敗しました",
    "failedLoadRequests2": "リクエストの読み込みに失敗しました",
    "failedAcceptRequest": "リクエストの承認に失敗しました",
    "failedRejectRequest": "リクエストの拒否に失敗しました",
    "pleaseSelectClubDot": "クラブを選択してください。",
    "enterClubPassword": "クラブパスワードを入力してください。",
    "checkingDot": "確認中...",
    "wrongPasswordDot": "パスワードが違います。",
    "joinedAsAdmin": "✅ 管理者として参加しました",
    "enterAdminPasswordPh": "管理者パスワード",
    "enterAdminPasswordHint": "管理者パスワードを入力してください",
    "checkingDotDot": "確認中...",
    "wrongAdminPw": "管理者パスワードが違います",
    "endingSession": "⏹ セッション終了中...",
    "sessionEnded": "✅ セッション終了",
    "clubCreatedAdmin": "を作成しました！あなたは管理者です。",
    "setPinTitle": "PIN設定（4桁）",
    "confirmPin": "PINを確認",
    "recoveryWordSecret": "回復キーワード（秘密）",
    "enterPin": "PINを入力",
    "recoveryWord": "回復キーワード",
    "newPin": "新しいPIN（4桁）",
    "confirmNewPin": "新しいPINを確認",
    "alreadyPlayingSession": "別のセッションで既にプレー中",
    "availableStatus": "利用可能",
    "searchToAddPlayer": "選手を検索して追加...",
    "tapToToggleGender": "タップして性別を切替",
    "startingRating": "開始レーティング",
    "removeBtn": "削除",
    "alreadyExists": "既に存在します",
    "currentlyPlayingSession": "現在別のセッションでプレー中",
    "liveNowTitle": "ライブ中",
    "recentSessions": "最近のセッション",
    "noActiveSessions": "現在アクティブなセッションはありません",
    "noRecentSessions": "最近のセッションが見つかりません",
    "playersCount": "選手",
    "roundsCount": "ラウンド",
    "setupProfileFirst": "まずプロフィールを設定してください。",
    "tapProfileIcon": "プロフィールアイコンをタップして名前を選択してください。",
    "noClubSelectedDash": "クラブが選択されていません。",
    "goToClubTab": "クラブタブでクラブに参加してください。",
    "couldNotLoadSessions": "セッションを読み込めませんでした。",
    "checkConnection": "接続を確認してください。",
    "retryBtn": "↺ 再試行",
    "pendingPrefix": "⏳ 保留中: ",
    "deleteSetConfirm": "セットを削除",
    "noClubSelectedWarn2": "⚠️ クラブが選択されていません。",
    "adminModeRequired": "⚠️ 管理者モードが必要です。",
    "noPlayersYetVault": "クラブにまだ選手がいません。Vaultで選手を追加してください。",
    "clubPasswordPh": "クラブパスワード",
    "clubNamePh": "クラブ名",
    "memberPasswordPh": "メンバーパスワード",
    "errorPrefix": "エラー: ",
    "playerPrefix": "選手 ",
    "sessionBadge": "セッション",
    "vsLabel": "VS",
    "playersSelected": "選択済み",
    "playersActive": "アクティブ",
    "pairSet": "ペア設定済み",
    "pairsSet": "ペア設定済み",
    "courtSingle": "コート",
    "courtPlural": "コート",
    "report": "レポート",
    "monthlyStats": "月間統計",
    "foundInClub": "が見つかりました:",
    "enterDefaultPwClaim": "デフォルトパスワードを入力して参加してください:",
    "claimAndJoin": "申請して参加",
    "historyBtn": "履歴"
  },
  "kr": {
    "home": "홈",
    "players": "선수",
    "rounds": "라운드",
    "summary": "요약",
    "language": "언어",
    "fontSize": "글자 크기",
    "reset": "초기화",
    "resetAll": "전체 초기화",
    "resetExcept": "경기만 초기화",
    "enterCourts": "코트 수 입력",
    "importPlayers": "플레이어 찾아보기 ▶",
    "gender": "성별",
    "male": "남성",
    "female": "여성",
    "import": "가져오기",
    "enterPlayerName": "선수 이름 입력",
    "fixedPairs2": "고정 페어 설정 (선택)",
    "pround": " 라운드",
    "nround": "라운드 시작 ",
    "endrounds": "종료 및 다음 라운드 ",
    "endSession": "세션 종료",
    "roundno": "라운드 ",
    "roundShort": "R",
    "rank": "순위",
    "name": "이름",
    "wins": "승리",
    "played": "경기 수",
    "rested": "휴식 수",
    "importExample": "이름,성별\n카리\n바바니",
    "Timer": "타이머",
    "min": "분",
    "selectPlayer1": "선수 1 선택",
    "selectPlayer2": "선수 2 선택",
    "small": "작게",
    "medium": "보통",
    "large": "크게",
    "maxcourts": "코트 수를 입력하세요",
    "sittingOut": "휴식 중:",
    "courts": "코트",
    "theme": "테마",
    "light": "라이트",
    "dark": "다크",
    "export": "내보내기",
    "exporthtml": "📄 요약 내보내기",
    "confirmResetAll": "모든 데이터를 초기화하시겠습니까?",
    "confirmResetGames": "경기만 초기화하시겠습니까?",
    "endRoundsConfirm": "라운드를 종료하시겠습니까?",
    "yes": "확인",
    "help": "도움말",
    "statusReady": "상태: 준비 완료",
    "statusProgress": "상태: 진행 중...",
    "minRounds": "워밍업 라운드",
    "roundSettings": "라운드 설정",
    "competitive": "경쟁 모드",
    "browsePlayersSub": "저장된 선수에서 선택",
    "appTitle": "스포츠 클럽 스케줄러",
    "tagline": "배드민턴 & 피클볼",
    "login": "로그인",
    "logout": "로그아웃",
    "createAccount": "계정 만들기",
    "claimAccount": "계정 신청",
    "email": "이메일",
    "password": "비밀번호",
    "confirmPassword": "비밀번호 확인",
    "newPassword": "새 비밀번호",
    "confirmNewPassword": "새 비밀번호 확인",
    "displayName": "표시 이름",
    "recoveryKeyword": "복구 키워드",
    "forgotPassword": "비밀번호 찾기",
    "resetPassword": "비밀번호 재설정",
    "userId": "사용자 ID",
    "nickname": "닉네임",
    "yourEmail": "이메일 주소",
    "myCard": "내 카드",
    "myClubs": "내 클럽",
    "dashboard": "대시보드",
    "fixedPairs": "고정 페어",
    "selectPlayers": "선수 선택",
    "startRounds": "라운드 시작",
    "watchSession": "세션 관전",
    "viewer": "관전자",
    "organiser": "주최자",
    "vault": "볼트",
    "chooseMode": "모드 선택",
    "howUsingApp": "앱 사용 방법을 선택하세요",
    "watchLive": "라이브 라운드 & 점수 관전",
    "runSession": "세션 운영, 게임 점수, 선수 관리",
    "clubAdmin": "클럽 관리 -- 선수, 요청, 관리",
    "roundOrganiser": "라운드 주최자",
    "vaultManager": "볼트 매니저",
    "myClubsTitle": "내 클럽",
    "findClub": "클럽 찾기",
    "joinClub": "참여",
    "leaveClub": "탈퇴",
    "noClubSelected": "클럽 미선택",
    "createClub": "클럽 만들기",
    "createNewClub": "새 클럽 만들기",
    "createYourClub": "클럽을 만드세요",
    "deleteClub": "클럽 삭제",
    "connectClub": "연결",
    "clubManagement": "클럽 관리",
    "noClubYet": "클럽이 없습니다. 만들어 보세요",
    "searchClub": "클럽 검색",
    "findRequest": "검색 & 요청",
    "submitRequest": "요청 제출",
    "requestSent": "요청이 전송되었습니다. 관리자 승인을 기다려 주세요.",
    "tapConnect": "탭하여 연결",
    "register": "등록",
    "modify": "수정",
    "requests": "요청",
    "playing": "경기 중",
    "onCourtNow": "현재 경기 중",
    "pendingApproval": "승인 대기 중",
    "playersInClub": "클럽 선수",
    "tapToEdit": "탭하여 편집",
    "joinAClub": "클럽 참여",
    "newClub": "새 클럽",
    "removeClub": "클럽 제거",
    "loadingRequests": "요청 불러오는 중...",
    "addPlayer": "선수 추가",
    "editPlayer": "선수 편집",
    "addRemove": "추가 · 제거",
    "alwaysTogether": "항상 함께",
    "addAtLeast4": "4명 이상 추가하세요",
    "myProfile": "내 프로필",
    "recentMatches": "최근 경기",
    "sessionStats": "세션 통계",
    "sessions": "세션",
    "allTimeWins": "전체 승리",
    "allTimeLosses": "전체 패배",
    "globalRating": "글로벌 레이팅",
    "globalPoints": "글로벌 포인트",
    "clubRating": "클럽 레이팅",
    "clubPoints": "클럽 포인트",
    "thisWeek": "이번 주",
    "thisMonth": "이번 달",
    "thisYear": "올해",
    "signInStats": "통계를 보려면 로그인하세요",
    "trackStats": "레이팅, 승리 및 경기 기록 추적",
    "appearance": "외관",
    "tileStyle": "타일 스타일",
    "flat": "플랫",
    "glow": "글로우",
    "color": "컬러",
    "subscription": "구독",
    "currentMode": "현재 모드",
    "freeTrial": "🎉 무료 체험",
    "restorePurchase": "구매 복원",
    "subscribeNow": "지금 구독",
    "trialEnded": "무료 체험이 종료되었습니다",
    "add": "추가",
    "cancel": "취소",
    "save": "변경 저장",
    "clear": "지우기",
    "clearHistory": "기록 지우기",
    "clearFavorites": "즐겨찾기 지우기",
    "delete": "삭제",
    "replace": "교체",
    "skip": "건너뛰기",
    "start": "시작",
    "end": "종료",
    "switch": "전환",
    "change": "변경",
    "info": "정보",
    "preview": "미리보기",
    "loading": "불러오는 중...",
    "liveSessions": "라이브 세션",
    "liveNow": "현재 라이브",
    "noLiveSessions": "라이브 세션 없음",
    "favourite": "즐겨찾기",
    "history": "기록",
    "whoAreYou": "당신은 누구인가요?",
    "notSelected": "미선택",
    "getStarted": "시작하기",
    "welcome": "환영합니다",
    "selectFromSaved": "저장된 선수에서 선택",
    "selectNameProfile": "프로필 설정을 위해 이름을 선택하세요",
    "asRegisteredByAdmin": "관리자가 등록한 이름",
    "givenByAdmin": "관리자 제공",
    "minSixChars": "최소 6자",
    "toResetPassword": "비밀번호 재설정용",
    "yourNameAlias": "이름 또는 별명",
    "defaultPassword": "기본 비밀번호",
    "tile": "타일",
    "wideTile": "와이드 타일",
    "description": "설명",
    "addPlayer2": "추가",
    "addPlayers": "선수 추가",
    "adminAccess": "관리자 액세스",
    "adminBadge": "ADMIN",
    "backHome": "‹ 홈",
    "browseBtn": "찾아보기",
    "claimMyAccount": "계정 신청",
    "clearBtn": "지우기",
    "clubLabel": "클럽",
    "clubRatingLabel": "클럽 레이팅",
    "clubSchedulerPro": "CLUB Scheduler Pro",
    "connectToClub": "클럽 연결",
    "connectToClubBadminton": "🏸 클럽 연결",
    "court": "코트",
    "courtsLabel": "코트",
    "editPlayerName": "선수 이름 편집",
    "emailLabel": "이메일",
    "endBtn": "종료",
    "favouriteBtn": "즐겨찾기",
    "findAClub": "클럽 찾기",
    "findYourClub": "클럽 찾기",
    "globalRatingLabel": "글로벌 레이팅",
    "goBtn": "시작 ›",
    "helpGuide": "도움말 및 가이드",
    "howUsingAppToday": "오늘 앱을 어떻게 사용하시겠습니까?",
    "inProgress": "진행 중",
    "joinBtn": "참여",
    "joinRequests": "참여 요청",
    "lessOneShuttle": "연간 셔틀콕 1개 미만",
    "liveBadge": "LIVE",
    "loadingClubs": "-- 클럽 불러오는 중... --",
    "lockBtn": "잠금",
    "markAllWinners": "모든 경기의 승자를 표시해 주세요",
    "markWinner": "승자 표시",
    "modifyPlayers": "선수 수정",
    "newBadge": "NEW",
    "nextRound": "다음 라운드",
    "pairsLabel": "페어",
    "passwordBlank": "비밀번호 (변경 없으면 공백)",
    "passwordLabel": "비밀번호",
    "player1": "선수 1",
    "player2": "선수 2",
    "playingNow": "현재 경기 중",
    "readyBadge": "READY",
    "refresh": "↻ 새로고침",
    "registerPlayers": "선수 등록",
    "removePlayer": "선수 삭제",
    "replaceBtn": "교체",
    "resendCode": "코드 재전송",
    "resetRoundsOnly": "라운드만 초기화",
    "resting": "휴식 중",
    "round": "라운드",
    "roundOrganiserDesc": "세션 운영, 게임 점수, 선수 관리",
    "roundsLabel": "라운드",
    "saveSet": "세트 저장",
    "searchByClubName": "클럽 이름으로 검색 및 요청",
    "selectClub": "-- 클럽 선택 --",
    "selectClubDelete": "-- 삭제할 클럽 선택 --",
    "selectClubOption": "-- 클럽 선택 --",
    "sessionStatsLabel": "세션 통계",
    "settings": "설정",
    "skipBtn": "건너뛰기",
    "startBtn": "시작",
    "startRoundsBtn": "라운드 시작 ›",
    "subFeature1": "✓ 완전한 통계 및 세션 기록",
    "subFeature2": "✓ 라이브 라운드 및 점수",
    "subFeature3": "✓ 주최자 모드 -- 세션 운영",
    "subFeature4": "✓ 선수 및 고정 페어 관리",
    "subFeature5": "✓ 관전자 모드 -- 라이브 점수 관전",
    "summaryLabel": "요약",
    "switchBtn": "전환",
    "sync": "↻ 동기화",
    "unlockBtn": "잠금 해제",
    "useAdminMode": "Vault 모드로 전체 관리 액세스 사용",
    "userBadge": "USER",
    "userID": "사용자 ID",
    "vaultManagerDesc": "클럽 관리 -- 선수, 요청, 관리",
    "verifyEmail": "이메일 인증",
    "viewerBadge": "VIEWER",
    "watchLiveDesc": "라이브 라운드 & 점수 관전",
    "welcomeTitle": "환영합니다",
    "notConnected": "연결되지 않음",
    "setupBadge": "SETUP",
    "memberMsg": "이 클럽의 회원입니다.",
    "club": "클럽",
    "clubs": "클럽",
    "pending": "대기 중",
    "loginToSeeClubs": "클럽을 보려면 로그인하세요",
    "noClubsYetSearch": "클럽이 없습니다. 아래에서 검색하여 참여하세요.",
    "noClubsYet": "클럽이 없습니다.",
    "couldNotLoadClubs": "클럽을 불러올 수 없습니다.",
    "searching": "검색 중...",
    "noClubsFoundFor": "검색 결과 없음",
    "joined": "참여 완료",
    "welcomeBack": "다시 오셨군요",
    "requestPending": "요청 대기 중",
    "checking": "확인 중...",
    "requestSentTitle": "요청이 전송되었습니다!",
    "waitingAdminApproval": "관리자 승인을 기다리고 있습니다.",
    "doneBtn": "완료 ✓",
    "setUpBtn": "설정 ›",
    "alreadyTaken": "이미 사용 중입니다",
    "chooseDifferentNickname": "이 클럽에서 다른 닉네임을 선택하세요",
    "noRoundsYet": "라운드가 없습니다",
    "joinClubToPlay": "경기 중인 선수를 보려면 클럽에 참여하세요.",
    "noPlayersLocked": "현재 잠긴 선수가 없습니다.",
    "failedLoadConnection": "불러오기 실패. 연결을 확인하세요.",
    "noPlayersInDb": "아직 선수가 없습니다.",
    "adminAccessRequired": "🔒 관리자 액세스가 필요합니다.",
    "joinClubToManage": "선수를 관리하려면 클럽에 참여하세요.",
    "failedLoadPlayers": "선수 불러오기 실패.",
    "noPlayersMatch": "검색 조건에 맞는 선수가 없습니다.",
    "noClubSelectedJoin": "⚠️ 클럽이 선택되지 않았습니다. 먼저 클럽에 참여하세요.",
    "playerNotFound": "선수를 찾을 수 없습니다.",
    "noPlayersAvailable": "사용 가능한 선수가 없습니다",
    "pleaseWait": "잠시 기다려 주세요...",
    "selectClubTitle": "클럽 선택",
    "searchFailed": "검색 실패. 다시 시도하세요.",
    "noClubsFound": "클럽을 찾을 수 없습니다. 이름을 확인하세요.",
    "sendingRequest": "요청 전송 중...",
    "connectClubFirst": "먼저 클럽에 연결하세요.",
    "noPendingRequests": "대기 중인 요청이 없습니다.",
    "failedLoadRequests": "요청 불러오기 실패.",
    "forceEndSession": "⏹ 세션 강제 종료",
    "ending": "종료 중...",
    "typeClubSearch": "클럽 이름을 입력하여 검색...",
    "playerSingular": "선수",
    "playerPlural": "선수",
    "releaseAll": "🔓 전체 해제",
    "badgeActive": "활성",
    "badgeMember": "회원",
    "badgePending": "대기 중",
    "asNick": "로서",
    "requestPendingText": "요청 대기 중",
    "winsShort": "승",
    "lossesShort": "패",
    "sessionActive": "세션 시작!",
    "registeredBadge": "✅ 등록됨",
    "noAccountBadge": "계정 없음",
    "genderMale": "남성",
    "genderFemale": "여성",
    "genderAll": "전체",
    "searchPlayers": "선수 검색...",
    "searchPlayerDot": "선수 검색...",
    "searchHelp": "도움말 검색...",
    "noResultsFound": "결과를 찾을 수 없습니다",
    "adminBadgeFull": "🔑 관리자",
    "userBadgeFull": "👤 사용자",
    "changePassword": "🔑 비밀번호 변경",
    "wrongPassword": "잘못된 비밀번호입니다. 다시 시도하세요.",
    "passwordMin4": "비밀번호는 4자 이상이어야 합니다.",
    "passwordsNotMatch": "비밀번호가 일치하지 않습니다",
    "passwordMin6": "비밀번호는 6자 이상이어야 합니다",
    "memberAdminDiff": "회원 비밀번호와 관리자 비밀번호는 달라야 합니다.",
    "emailRequired": "이메일은 필수입니다",
    "emailInvalid": "유효한 이메일을 입력하세요",
    "displayNameMin2": "표시 이름은 2자 이상이어야 합니다",
    "recoveryMin3": "복구 키워드는 3자 이상이어야 합니다",
    "emailAlreadyReg": "이미 등록된 이메일입니다. 로그인하세요.",
    "signupFailed": "가입 실패. 다시 시도하세요.",
    "enterEmail": "이메일을 입력하세요",
    "enterPassword": "비밀번호를 입력하세요",
    "noAccountEmail": "이 이메일로 등록된 계정이 없습니다",
    "wrongPasswordLogin": "잘못된 비밀번호",
    "loginFailed": "로그인 실패. 다시 시도하세요.",
    "enterRecovery": "복구 키워드를 입력하세요",
    "emailRecoveryWrong": "이메일 또는 복구 키워드가 잘못되었습니다",
    "resetFailed": "재설정 실패. 다시 시도하세요.",
    "nicknameNotFound": "이 클럽에서 닉네임을 찾을 수 없습니다. 관리자에게 확인하세요.",
    "alreadyClaimed": "이 계정은 이미 신청되었습니다. 로그인하거나 비밀번호를 재설정하세요.",
    "defaultPwWrong": "기본 비밀번호가 잘못되었습니다. 관리자에게 확인하세요.",
    "emailAlreadyUsed": "이 이메일은 이미 등록되어 있습니다. 다른 이메일을 사용하세요.",
    "nameCannotBeEmpty": "이름은 비워둘 수 없습니다.",
    "saving": "저장 중...",
    "saved": "✅ 저장됨!",
    "enterClubName": "클럽 이름을 입력하세요.",
    "enterMemberPw": "회원 비밀번호를 입력하세요.",
    "enterAdminPw": "관리자 비밀번호를 입력하세요.",
    "selectPlayersStep": "선수 선택",
    "addAtLeast4Step": "시작하려면 4명 이상의 선수를 추가하세요",
    "fixedPairsStep": "고정 페어",
    "fixedPairsOptional": "선택 -- 항상 함께 플레이하는 선수를 페어로 지정",
    "skippedOptional": "건너뜀 (선택)",
    "courtSettings": "코트 설정",
    "setCourtMode": "코트 및 플레이 모드 설정",
    "randomMode": "랜덤",
    "startRoundsStep": "라운드 시작",
    "allSetReady": "준비 완료 -- 플레이 시작!",
    "sessionInProgress": "세션 진행 중",
    "optional": "선택",
    "liveSession": "라이브 세션",
    "youMemberMultipleClubs": "여러 클럽의 회원입니다",
    "requestToJoin": "참여 요청 ›",
    "accept": "✓ 수락",
    "reject": "✗ 거부",
    "verifyEmailTitle": "이메일 인증",
    "enterSixDigit": "전송된 6자리 코드를 입력하세요",
    "verifyBtn": "인증",
    "enterSixDigitHint": "6자리 코드 입력",
    "codeResent": "✅ 코드가 재전송되었습니다",
    "passwordReset": "✅ 비밀번호가 재설정되었습니다! 로그인하세요.",
    "noClubsFoundDot": "클럽을 찾을 수 없습니다.",
    "couldNotLoadClubsErr": "❌ 클럽을 불러올 수 없습니다:",
    "pleaseSelectClub": "클럽을 선택하세요.",
    "enterPasswordHint": "비밀번호를 입력하세요.",
    "enterMemberPwHint": "회원 비밀번호를 입력하세요.",
    "wrongPasswordHint": "잘못된 비밀번호입니다.",
    "joinedSuccessfully": "✅ 참여했습니다",
    "connectedAsMember": "✅ 회원으로 연결되었습니다",
    "noSessionData": "세션 데이터가 없습니다.<br>먼저 라운드를 완료하세요.",
    "noSessionDataAvail": "세션 데이터가 없습니다.",
    "couldNotLoadSession": "세션 데이터를 불러올 수 없습니다.",
    "today": "오늘",
    "yesterday": "어제",
    "forceEndConfirm": "이 세션을 강제 종료하시겠습니까? 취소할 수 없습니다.",
    "rookie": "초보자",
    "clubLevel": "클럽",
    "competitiveLevel": "경쟁",
    "advancedLevel": "고급",
    "eliteLevel": "엘리트",
    "notSelectedProfile": "미선택",
    "loadingPlayers": "선수 불러오는 중...",
    "noPlayersInClub": "클럽에서 선수를 찾을 수 없습니다.",
    "pinMustBe4": "PIN은 정확히 4자리여야 합니다.",
    "pinsNotMatch": "PIN이 일치하지 않습니다.",
    "recoveryTooShort": "복구 키워드가 너무 짧습니다.",
    "savingPin": "⏳ 저장 중...",
    "failedSave": "저장 실패. 다시 시도하세요.",
    "playerNotFoundPin": "선수를 찾을 수 없습니다.",
    "wrongPin": "❌ 잘못된 PIN. 다시 시도하세요.",
    "wrongRecovery": "❌ 잘못된 복구 키워드.",
    "pinMust4": "PIN은 4자리여야 합니다.",
    "subscribedPro": "✅ 구독 완료! Pro에 오신 것을 환영합니다.",
    "purchaseCancelled": "구매가 취소되었습니다.",
    "billingAppOnly": "결제는 앱에서만 가능합니다.",
    "purchaseRestored": "✅ 구매가 복원되었습니다!",
    "noActiveSubscription": "활성 구독을 찾을 수 없습니다.",
    "couldNotRestore": "구매를 복원할 수 없습니다.",
    "daysRemaining": "일 남음",
    "trialEndedSub": "🔒 체험 종료",
    "subscribeToContInue": "계속하려면 구독하세요",
    "activeSubscription": "✅ 활성",
    "subscribed": "구독 중",
    "noRegisteredPlayers": "등록된 선수를 찾을 수 없습니다",
    "clearHistoryConfirm": "기록을 지우시겠습니까?",
    "clearFavoritesConfirm": "즐겨찾기를 지우시겠습니까?",
    "helpUnavailable": "도움말을 사용할 수 없습니다. 연결을 확인하세요.",
    "stillNeedHelp": "도움이 더 필요하신가요? 지원에 문의하세요",
    "syncing": "🔄 동기화 중...",
    "noClubSelectedWarn": "⚠️ 클럽이 선택되지 않았습니다",
    "noPlayersFoundWarn": "⚠️ 선수를 찾을 수 없습니다",
    "offlineCache": "⚠️ 오프라인 -- 캐시 사용 중",
    "welcomeToApp": "스포츠 클럽 스케줄러에 오신 것을 환영합니다",
    "connectClubToStart": "클럽에 연결하여 시작하세요.",
    "goToVault": "Vault로 이동",
    "startGame": "시작",
    "readyGame": "준비 완료",
    "inProgressGame": "진행 중",
    "noneGame": "없음",
    "emptyGame": "(비어 있음)",
    "releaseFromSession": "활성 세션에서?",
    "releaseAllConfirm": "잠긴 모든 선수를 해제하시겠습니까?",
    "adminRole": "· 관리자",
    "userRole": "· 사용자",
    "leaveClubConfirm": "이 클럽을 탈퇴하시겠습니까?",
    "leaveVaultConfirm": "이 클럽을 탈퇴하시겠습니까? Vault 접근을 위해 재연결이 필요합니다.",
    "awaitingApproval": "의 관리자 승인을 기다리고 있습니다. 나중에 확인하세요.",
    "yourRequestToJoin": "참여 요청:",
    "notAvailable": "사용 불가",
    "creatingClub": "생성 중...",
    "creatingClubDot": "클럽 생성 중...",
    "selectClubToDelete": "삭제할 클럽을 선택하세요.",
    "verifyingDot": "확인 중...",
    "clubNotFound": "클럽을 찾을 수 없습니다.",
    "wrongAdminPassword": "관리자 비밀번호가 잘못되었습니다.",
    "playerNicknamePh": "선수 닉네임",
    "defaultPasswordPh": "예: club123",
    "enterDefaultPwAll": "모든 선수의 기본 비밀번호를 입력하세요.",
    "registeringDot": "등록 중...",
    "enterNickname": "닉네임을 입력하세요.",
    "enterDefaultPw": "기본 비밀번호를 설정하세요.",
    "nicknameExists": "이 클럽에 이미 있는 닉네임입니다.",
    "passwordsNotMatchDot": "비밀번호가 일치하지 않습니다.",
    "justStarted": "방금 시작됨",
    "selectYourClub": "클럽을 선택하세요",
    "enterYourNickname": "닉네임을 입력하세요",
    "enterDefaultPassword": "기본 비밀번호 입력",
    "sendingVerification": "인증 코드 전송 중...",
    "claimFailed": "신청 실패. 다시 시도하세요.",
    "invalidOTP": "유효하지 않은 OTP",
    "otpExpired": "OTP가 만료되었습니다. 새로 요청하세요.",
    "accountNotFound": "계정을 찾을 수 없습니다",
    "pleaseLoginFirst": "먼저 로그인하세요",
    "invalidInviteCode": "유효하지 않은 초대 코드입니다. 주최자에게 확인하세요.",
    "failedToJoinClub": "클럽 참여 실패.",
    "searchFailed2": "검색 실패",
    "provideNickname": "닉네임을 입력하세요.",
    "failedSendRequest": "요청 전송 실패",
    "failedLoadRequests2": "요청 불러오기 실패",
    "failedAcceptRequest": "요청 승인 실패",
    "failedRejectRequest": "요청 거부 실패",
    "pleaseSelectClubDot": "클럽을 선택하세요.",
    "enterClubPassword": "클럽 비밀번호를 입력하세요.",
    "checkingDot": "확인 중...",
    "wrongPasswordDot": "비밀번호가 잘못되었습니다.",
    "joinedAsAdmin": "✅ 관리자로 참여했습니다",
    "enterAdminPasswordPh": "관리자 비밀번호",
    "enterAdminPasswordHint": "관리자 비밀번호를 입력하세요",
    "checkingDotDot": "확인 중...",
    "wrongAdminPw": "관리자 비밀번호가 잘못되었습니다",
    "endingSession": "⏹ 세션 종료 중...",
    "sessionEnded": "✅ 세션 종료됨",
    "clubCreatedAdmin": "이(가) 생성되었습니다! 당신은 관리자입니다.",
    "setPinTitle": "PIN 설정 (4자리)",
    "confirmPin": "PIN 확인",
    "recoveryWordSecret": "복구 단어 (비밀)",
    "enterPin": "PIN 입력",
    "recoveryWord": "복구 단어",
    "newPin": "새 PIN (4자리)",
    "confirmNewPin": "새 PIN 확인",
    "alreadyPlayingSession": "다른 세션에서 이미 플레이 중",
    "availableStatus": "사용 가능",
    "searchToAddPlayer": "선수를 검색하여 추가...",
    "tapToToggleGender": "탭하여 성별 전환",
    "startingRating": "시작 레이팅",
    "removeBtn": "삭제",
    "alreadyExists": "이미 존재합니다",
    "currentlyPlayingSession": "현재 다른 세션에서 플레이 중",
    "liveNowTitle": "라이브 중",
    "recentSessions": "최근 세션",
    "noActiveSessions": "현재 활성 세션이 없습니다",
    "noRecentSessions": "최근 세션을 찾을 수 없습니다",
    "playersCount": "선수",
    "roundsCount": "라운드",
    "setupProfileFirst": "먼저 프로필을 설정하세요.",
    "tapProfileIcon": "프로필 아이콘을 탭하여 이름을 선택하세요.",
    "noClubSelectedDash": "클럽이 선택되지 않았습니다.",
    "goToClubTab": "클럽 탭에서 클럽에 참여하세요.",
    "couldNotLoadSessions": "세션을 불러올 수 없습니다.",
    "checkConnection": "연결을 확인하세요.",
    "retryBtn": "↺ 재시도",
    "pendingPrefix": "⏳ 대기 중: ",
    "deleteSetConfirm": "세트 삭제",
    "noClubSelectedWarn2": "⚠️ 클럽이 선택되지 않았습니다.",
    "adminModeRequired": "⚠️ 관리자 모드가 필요합니다.",
    "noPlayersYetVault": "클럽에 아직 선수가 없습니다. Vault에서 선수를 추가하세요.",
    "clubPasswordPh": "클럽 비밀번호",
    "clubNamePh": "클럽 이름",
    "memberPasswordPh": "회원 비밀번호",
    "errorPrefix": "오류: ",
    "playerPrefix": "선수 ",
    "sessionBadge": "세션",
    "vsLabel": "VS",
    "playersSelected": "선택됨",
    "playersActive": "활성",
    "pairSet": "페어 설정됨",
    "pairsSet": "페어 설정됨",
    "courtSingle": "코트",
    "courtPlural": "코트",
    "report": "보고서",
    "monthlyStats": "월간 통계",
    "foundInClub": "에서 발견됨:",
    "enterDefaultPwClaim": "기본 비밀번호를 입력하여 참여하세요:",
    "claimAndJoin": "신청하고 참여",
    "historyBtn": "기록"
  },
  "vi": {
    "home": "Trang chủ",
    "players": "Người chơi",
    "rounds": "Vòng đấu",
    "summary": "Tóm tắt",
    "language": "Ngôn ngữ",
    "fontSize": "Cỡ chữ",
    "reset": "Đặt lại",
    "resetAll": "Đặt lại tất cả",
    "resetExcept": "Đặt lại trận đấu",
    "enterCourts": "Nhập số sân",
    "importPlayers": "Duyệt người chơi ▶",
    "gender": "Giới tính",
    "male": "Nam",
    "female": "Nữ",
    "import": "Nhập",
    "enterPlayerName": "Nhập tên người chơi",
    "fixedPairs2": "Cố định cặp đấu (Tùy chọn)",
    "pround": " Vòng",
    "nround": "Bắt đầu vòng ",
    "endrounds": "Kết thúc & Vòng tiếp theo ",
    "endSession": "Kết thúc phiên",
    "roundno": "Vòng ",
    "roundShort": "R",
    "rank": "Xếp hạng",
    "name": "Tên",
    "wins": "Chiến thắng",
    "played": "Số trận",
    "rested": "Số lần nghỉ",
    "importExample": "Tên,Giới tính\nKari\nBhavani",
    "Timer": "Hẹn giờ",
    "min": "phút",
    "selectPlayer1": "Chọn người chơi 1",
    "selectPlayer2": "Chọn người chơi 2",
    "small": "Nhỏ",
    "medium": "Vừa",
    "large": "Lớn",
    "maxcourts": "Nhập số sân",
    "sittingOut": "Đang nghỉ:",
    "courts": "Sân",
    "theme": "Chủ đề",
    "light": "Sáng",
    "dark": "Tối",
    "export": "Xuất",
    "exporthtml": "📄 Xuất bản tóm tắt",
    "confirmResetAll": "Bạn có muốn đặt lại tất cả không?",
    "confirmResetGames": "Bạn có muốn đặt lại trận đấu không?",
    "endRoundsConfirm": "Bạn có muốn kết thúc các vòng không?",
    "yes": "Có",
    "help": "Trợ giúp",
    "statusReady": "Trạng thái: Sẵn sàng",
    "statusProgress": "Trạng thái: Đang tiến hành...",
    "minRounds": "Vòng khởi động",
    "roundSettings": "Cài đặt vòng",
    "competitive": "Cạnh tranh",
    "browsePlayersSub": "Chọn từ danh sách đã lưu",
    "appTitle": "Lịch Trình Câu Lạc Bộ Thể Thao",
    "tagline": "Cầu Lông & Pickleball",
    "login": "Đăng Nhập",
    "logout": "Đăng Xuất",
    "createAccount": "Tạo Tài Khoản",
    "claimAccount": "Xác Nhận Tài Khoản",
    "email": "Email",
    "password": "Mật Khẩu",
    "confirmPassword": "Xác Nhận Mật Khẩu",
    "newPassword": "Mật Khẩu Mới",
    "confirmNewPassword": "Xác Nhận Mật Khẩu Mới",
    "displayName": "Tên Hiển Thị",
    "recoveryKeyword": "Từ Khóa Khôi Phục",
    "forgotPassword": "Quên mật khẩu?",
    "resetPassword": "Đặt Lại Mật Khẩu",
    "userId": "ID Người Dùng",
    "nickname": "Biệt Danh",
    "yourEmail": "Email Của Bạn",
    "myCard": "Thẻ Của Tôi",
    "myClubs": "CLB Của Tôi",
    "dashboard": "Bảng Điều Khiển",
    "fixedPairs": "Cặp Cố Định",
    "selectPlayers": "Chọn Người Chơi",
    "startRounds": "Bắt Đầu Vòng",
    "watchSession": "Xem Phiên",
    "viewer": "Khán Giả",
    "organiser": "Người Tổ Chức",
    "vault": "Kho",
    "chooseMode": "Chọn Chế Độ",
    "howUsingApp": "Chọn cách bạn sử dụng ứng dụng",
    "watchLive": "Xem vòng đấu & điểm số trực tiếp",
    "runSession": "Điều hành phiên, tính điểm, quản lý người chơi",
    "clubAdmin": "Quản trị CLB -- người chơi, yêu cầu, quản lý",
    "roundOrganiser": "Người Tổ Chức Vòng",
    "vaultManager": "Quản Lý Kho",
    "myClubsTitle": "CLB Của Tôi",
    "findClub": "Tìm CLB",
    "joinClub": "Tham Gia",
    "leaveClub": "Rời",
    "noClubSelected": "Chưa chọn CLB",
    "createClub": "Tạo CLB",
    "createNewClub": "Tạo CLB Mới",
    "createYourClub": "Tạo CLB Của Bạn",
    "deleteClub": "Xóa CLB",
    "connectClub": "Kết Nối",
    "clubManagement": "Quản Lý CLB",
    "noClubYet": "Chưa có CLB. Tạo một CLB để bắt đầu",
    "searchClub": "Tìm Kiếm CLB",
    "findRequest": "Tìm & yêu cầu",
    "submitRequest": "Gửi Yêu Cầu",
    "requestSent": "Đã gửi yêu cầu! Chờ admin phê duyệt.",
    "tapConnect": "Nhấn để kết nối",
    "register": "Đăng Ký",
    "modify": "Sửa Đổi",
    "requests": "Yêu Cầu",
    "playing": "Đang Chơi",
    "onCourtNow": "đang trên sân",
    "pendingApproval": "chờ phê duyệt",
    "playersInClub": "người chơi trong CLB",
    "tapToEdit": "nhấn để chỉnh sửa",
    "joinAClub": "tham gia CLB",
    "newClub": "CLB mới",
    "removeClub": "xóa CLB",
    "loadingRequests": "Đang tải yêu cầu...",
    "addPlayer": "Thêm Người Chơi",
    "editPlayer": "Chỉnh Sửa Người Chơi",
    "addRemove": "Thêm · Xóa",
    "alwaysTogether": "Luôn cùng nhau",
    "addAtLeast4": "Thêm ít nhất 4 người chơi",
    "myProfile": "Hồ Sơ Của Tôi",
    "recentMatches": "Trận Đấu Gần Đây",
    "sessionStats": "Thống Kê Phiên",
    "sessions": "Phiên",
    "allTimeWins": "Tổng Thắng",
    "allTimeLosses": "Tổng Thua",
    "globalRating": "Xếp Hạng Toàn Cầu",
    "globalPoints": "Điểm Toàn Cầu",
    "clubRating": "Xếp Hạng CLB",
    "clubPoints": "Điểm CLB",
    "thisWeek": "Tuần Này",
    "thisMonth": "Tháng Này",
    "thisYear": "Năm Nay",
    "signInStats": "Đăng nhập để xem thống kê",
    "trackStats": "Theo dõi xếp hạng, thắng và lịch sử trận đấu.",
    "appearance": "Giao Diện",
    "tileStyle": "Kiểu Ô",
    "flat": "Phẳng",
    "glow": "Phát Sáng",
    "color": "Màu Sắc",
    "subscription": "Đăng Ký",
    "currentMode": "Chế Độ Hiện Tại",
    "freeTrial": "🎉 Dùng thử miễn phí",
    "restorePurchase": "Khôi Phục Mua Hàng",
    "subscribeNow": "Đăng Ký Ngay",
    "trialEnded": "Thời gian dùng thử đã kết thúc",
    "add": "Thêm",
    "cancel": "Hủy",
    "save": "Lưu Thay Đổi",
    "clear": "Xóa",
    "clearHistory": "Xóa Lịch Sử",
    "clearFavorites": "Xóa Yêu Thích",
    "delete": "Xóa",
    "replace": "Thay Thế",
    "skip": "Bỏ Qua",
    "start": "Bắt Đầu",
    "end": "Kết Thúc",
    "switch": "Chuyển Đổi",
    "change": "Thay Đổi",
    "info": "Thông Tin",
    "preview": "Xem Trước",
    "loading": "Đang tải...",
    "liveSessions": "Phiên Trực Tiếp",
    "liveNow": "Đang Trực Tiếp",
    "noLiveSessions": "Không có phiên trực tiếp",
    "favourite": "Yêu Thích",
    "history": "Lịch Sử",
    "whoAreYou": "Bạn là ai?",
    "notSelected": "Chưa chọn",
    "getStarted": "Bắt Đầu",
    "welcome": "Chào Mừng",
    "selectFromSaved": "Chọn từ danh sách đã lưu",
    "selectNameProfile": "Chọn tên để cá nhân hóa hồ sơ",
    "asRegisteredByAdmin": "như admin đã đăng ký",
    "givenByAdmin": "được admin cung cấp",
    "minSixChars": "tối thiểu 6 ký tự",
    "toResetPassword": "để đặt lại mật khẩu nếu quên",
    "yourNameAlias": "tên hoặc bí danh của bạn",
    "defaultPassword": "Mật Khẩu Mặc Định",
    "tile": "Ô",
    "wideTile": "Ô Rộng",
    "description": "Mô tả",
    "addPlayer2": "Thêm",
    "addPlayers": "Thêm người chơi",
    "adminAccess": "Quyền quản trị",
    "adminBadge": "ADMIN",
    "backHome": "‹ Trang chủ",
    "browseBtn": "Duyệt",
    "claimMyAccount": "Xác nhận tài khoản",
    "clearBtn": "Xóa",
    "clubLabel": "CLB",
    "clubRatingLabel": "Xếp hạng CLB",
    "clubSchedulerPro": "CLUB Scheduler Pro",
    "connectToClub": "Kết nối CLB",
    "connectToClubBadminton": "🏸 Kết nối CLB",
    "court": "Sân",
    "courtsLabel": "Sân",
    "editPlayerName": "Sửa tên người chơi",
    "emailLabel": "Email",
    "endBtn": "Kết thúc",
    "favouriteBtn": "Yêu thích",
    "findAClub": "Tìm CLB",
    "findYourClub": "Tìm CLB của bạn",
    "globalRatingLabel": "Xếp hạng toàn cầu",
    "goBtn": "Bắt đầu ›",
    "helpGuide": "Trợ giúp & Hướng dẫn",
    "howUsingAppToday": "Hôm nay bạn sử dụng ứng dụng như thế nào?",
    "inProgress": "Đang diễn ra",
    "joinBtn": "Tham gia",
    "joinRequests": "Yêu cầu tham gia",
    "lessOneShuttle": "Ít hơn một cầu mỗi năm",
    "liveBadge": "LIVE",
    "loadingClubs": "-- Đang tải CLB... --",
    "lockBtn": "Khóa",
    "markAllWinners": "Vui lòng đánh dấu người thắng cho tất cả trận",
    "markWinner": "Đánh dấu người thắng",
    "modifyPlayers": "Chỉnh sửa người chơi",
    "newBadge": "MỚI",
    "nextRound": "Vòng tiếp theo",
    "pairsLabel": "Cặp",
    "passwordBlank": "Mật khẩu (để trống nếu không đổi)",
    "passwordLabel": "Mật khẩu",
    "player1": "Người chơi 1",
    "player2": "Người chơi 2",
    "playingNow": "Đang chơi",
    "readyBadge": "SẴN SÀNG",
    "refresh": "↻ Làm mới",
    "registerPlayers": "Đăng ký người chơi",
    "removePlayer": "Xóa người chơi",
    "replaceBtn": "Thay thế",
    "resendCode": "Gửi lại mã",
    "resetRoundsOnly": "Chỉ đặt lại vòng đấu",
    "resting": "Nghỉ",
    "round": "Vòng",
    "roundOrganiserDesc": "Điều hành phiên, tính điểm, quản lý người chơi",
    "roundsLabel": "Vòng đấu",
    "saveSet": "Lưu set",
    "searchByClubName": "Tìm theo tên CLB và gửi yêu cầu",
    "selectClub": "-- Chọn CLB --",
    "selectClubDelete": "-- Chọn CLB để xóa --",
    "selectClubOption": "-- Chọn CLB --",
    "sessionStatsLabel": "Thống kê phiên",
    "settings": "Cài đặt",
    "skipBtn": "Bỏ qua",
    "startBtn": "Bắt đầu",
    "startRoundsBtn": "Bắt đầu vòng ›",
    "subFeature1": "✓ Thống kê đầy đủ & lịch sử phiên",
    "subFeature2": "✓ Vòng đấu & tính điểm trực tiếp",
    "subFeature3": "✓ Chế độ tổ chức -- điều hành phiên",
    "subFeature4": "✓ Quản lý người chơi & cặp cố định",
    "subFeature5": "✓ Chế độ khán giả -- xem điểm trực tiếp",
    "summaryLabel": "Tóm tắt",
    "switchBtn": "Chuyển đổi",
    "sync": "↻ Đồng bộ",
    "unlockBtn": "Mở khóa",
    "useAdminMode": "Dùng chế độ Vault để có toàn quyền quản trị",
    "userBadge": "USER",
    "userID": "ID người dùng",
    "vaultManagerDesc": "Quản trị CLB -- người chơi, yêu cầu, quản lý",
    "verifyEmail": "Xác minh email",
    "viewerBadge": "VIEWER",
    "watchLiveDesc": "Xem vòng đấu & điểm số trực tiếp",
    "welcomeTitle": "Chào mừng",
    "notConnected": "Chưa kết nối",
    "setupBadge": "SETUP",
    "memberMsg": "Bạn là thành viên của CLB này.",
    "club": "CLB",
    "clubs": "CLB",
    "pending": "đang chờ",
    "loginToSeeClubs": "Đăng nhập để xem CLB",
    "noClubsYetSearch": "Chưa có CLB. Tìm kiếm bên dưới để tham gia.",
    "noClubsYet": "Chưa có CLB.",
    "couldNotLoadClubs": "Không thể tải CLB.",
    "searching": "Đang tìm kiếm...",
    "noClubsFoundFor": "Không tìm thấy CLB cho",
    "joined": "Đã tham gia",
    "welcomeBack": "Chào mừng trở lại",
    "requestPending": "Yêu cầu đang chờ",
    "checking": "Đang kiểm tra...",
    "requestSentTitle": "Đã gửi yêu cầu!",
    "waitingAdminApproval": "Đang chờ admin phê duyệt.",
    "doneBtn": "Xong ✓",
    "setUpBtn": "Thiết lập ›",
    "alreadyTaken": "đã được sử dụng trong",
    "chooseDifferentNickname": "Chọn biệt danh khác cho CLB này",
    "noRoundsYet": "Chưa có vòng đấu",
    "joinClubToPlay": "Tham gia CLB để xem người đang chơi.",
    "noPlayersLocked": "Hiện không có người chơi nào bị khóa.",
    "failedLoadConnection": "Tải thất bại. Kiểm tra kết nối.",
    "noPlayersInDb": "Chưa có người chơi nào.",
    "adminAccessRequired": "🔒 Yêu cầu quyền quản trị.",
    "joinClubToManage": "Tham gia CLB để quản lý người chơi.",
    "failedLoadPlayers": "Tải người chơi thất bại.",
    "noPlayersMatch": "Không có người chơi phù hợp.",
    "noClubSelectedJoin": "⚠️ Chưa chọn CLB. Tham gia CLB trước.",
    "playerNotFound": "Không tìm thấy người chơi.",
    "noPlayersAvailable": "Không có người chơi nào",
    "pleaseWait": "Vui lòng chờ...",
    "selectClubTitle": "Chọn CLB",
    "searchFailed": "Tìm kiếm thất bại. Thử lại.",
    "noClubsFound": "Không tìm thấy CLB. Kiểm tra tên.",
    "sendingRequest": "Đang gửi yêu cầu...",
    "connectClubFirst": "Kết nối CLB trước.",
    "noPendingRequests": "Không có yêu cầu đang chờ.",
    "failedLoadRequests": "Tải yêu cầu thất bại.",
    "forceEndSession": "⏹ Kết thúc phiên bắt buộc",
    "ending": "Đang kết thúc...",
    "typeClubSearch": "Nhập tên CLB để tìm kiếm...",
    "playerSingular": "người chơi",
    "playerPlural": "người chơi",
    "releaseAll": "🔓 Giải phóng tất cả",
    "badgeActive": "Đang hoạt động",
    "badgeMember": "Thành viên",
    "badgePending": "Đang chờ",
    "asNick": "là",
    "requestPendingText": "Yêu cầu đang chờ",
    "winsShort": "T",
    "lossesShort": "B",
    "sessionActive": "Phiên đã bắt đầu!",
    "registeredBadge": "✅ đã đăng ký",
    "noAccountBadge": "chưa có tài khoản",
    "genderMale": "Nam",
    "genderFemale": "Nữ",
    "genderAll": "Tất cả",
    "searchPlayers": "Tìm người chơi...",
    "searchPlayerDot": "Tìm người chơi...",
    "searchHelp": "Tìm trợ giúp...",
    "noResultsFound": "Không tìm thấy kết quả",
    "adminBadgeFull": "🔑 Quản trị",
    "userBadgeFull": "👤 Người dùng",
    "changePassword": "🔑 Đổi mật khẩu",
    "wrongPassword": "Sai mật khẩu. Thử lại.",
    "passwordMin4": "Mật khẩu phải ít nhất 4 ký tự.",
    "passwordsNotMatch": "Mật khẩu không khớp",
    "passwordMin6": "Mật khẩu phải ít nhất 6 ký tự",
    "memberAdminDiff": "Mật khẩu thành viên và quản trị phải khác nhau.",
    "emailRequired": "Email là bắt buộc",
    "emailInvalid": "Vui lòng nhập email hợp lệ",
    "displayNameMin2": "Tên hiển thị phải ít nhất 2 ký tự",
    "recoveryMin3": "Từ khóa khôi phục phải ít nhất 3 ký tự",
    "emailAlreadyReg": "Email đã được đăng ký. Vui lòng đăng nhập.",
    "signupFailed": "Đăng ký thất bại. Thử lại.",
    "enterEmail": "Vui lòng nhập email",
    "enterPassword": "Vui lòng nhập mật khẩu",
    "noAccountEmail": "Không tìm thấy tài khoản với email này",
    "wrongPasswordLogin": "Sai mật khẩu",
    "loginFailed": "Đăng nhập thất bại. Thử lại.",
    "enterRecovery": "Vui lòng nhập từ khóa khôi phục",
    "emailRecoveryWrong": "Email hoặc từ khóa khôi phục không đúng",
    "resetFailed": "Đặt lại thất bại. Thử lại.",
    "nicknameNotFound": "Không tìm thấy biệt danh trong CLB này. Kiểm tra với quản trị.",
    "alreadyClaimed": "Tài khoản này đã được xác nhận. Đăng nhập hoặc đặt lại mật khẩu.",
    "defaultPwWrong": "Mật khẩu mặc định không đúng. Kiểm tra với quản trị.",
    "emailAlreadyUsed": "Email này đã được đăng ký. Dùng email khác.",
    "nameCannotBeEmpty": "Tên không được để trống.",
    "saving": "Đang lưu...",
    "saved": "✅ Đã lưu!",
    "enterClubName": "Nhập tên CLB.",
    "enterMemberPw": "Nhập mật khẩu thành viên.",
    "enterAdminPw": "Nhập mật khẩu quản trị.",
    "selectPlayersStep": "Chọn người chơi",
    "addAtLeast4Step": "Thêm ít nhất 4 người chơi để bắt đầu",
    "fixedPairsStep": "Cặp cố định",
    "fixedPairsOptional": "Tùy chọn -- ghép người chơi luôn chơi cùng nhau",
    "skippedOptional": "Bỏ qua (tùy chọn)",
    "courtSettings": "Cài đặt sân",
    "setCourtMode": "Đặt sân và chế độ chơi",
    "randomMode": "Ngẫu nhiên",
    "startRoundsStep": "Bắt đầu vòng",
    "allSetReady": "Sẵn sàng -- bắt đầu chơi!",
    "sessionInProgress": "Phiên đang diễn ra",
    "optional": "Tùy chọn",
    "liveSession": "phiên trực tiếp",
    "youMemberMultipleClubs": "Bạn là thành viên của nhiều CLB",
    "requestToJoin": "Yêu cầu tham gia ›",
    "accept": "✓ Chấp nhận",
    "reject": "✗ Từ chối",
    "verifyEmailTitle": "Xác minh email",
    "enterSixDigit": "Nhập mã 6 chữ số đã gửi đến",
    "verifyBtn": "Xác minh",
    "enterSixDigitHint": "Nhập mã 6 chữ số",
    "codeResent": "✅ Đã gửi lại mã",
    "passwordReset": "✅ Đặt lại mật khẩu thành công! Vui lòng đăng nhập.",
    "noClubsFoundDot": "Không tìm thấy CLB.",
    "couldNotLoadClubsErr": "❌ Không thể tải CLB:",
    "pleaseSelectClub": "Vui lòng chọn CLB.",
    "enterPasswordHint": "Nhập mật khẩu.",
    "enterMemberPwHint": "Nhập mật khẩu thành viên.",
    "wrongPasswordHint": "Sai mật khẩu.",
    "joinedSuccessfully": "✅ Đã tham gia thành công",
    "connectedAsMember": "✅ Đã kết nối với tư cách thành viên",
    "noSessionData": "Chưa có dữ liệu phiên.<br>Hoàn thành một số vòng trước.",
    "noSessionDataAvail": "Không có dữ liệu phiên.",
    "couldNotLoadSession": "Không thể tải dữ liệu phiên.",
    "today": "Hôm nay",
    "yesterday": "Hôm qua",
    "forceEndConfirm": "Kết thúc phiên này không? Không thể hoàn tác.",
    "rookie": "Tân binh",
    "clubLevel": "CLB",
    "competitiveLevel": "Cạnh tranh",
    "advancedLevel": "Nâng cao",
    "eliteLevel": "Tinh hoa",
    "notSelectedProfile": "Chưa chọn",
    "loadingPlayers": "Đang tải người chơi...",
    "noPlayersInClub": "Không tìm thấy người chơi trong CLB.",
    "pinMustBe4": "PIN phải đúng 4 chữ số.",
    "pinsNotMatch": "PIN không khớp.",
    "recoveryTooShort": "Từ khóa khôi phục quá ngắn.",
    "savingPin": "⏳ Đang lưu...",
    "failedSave": "Lưu thất bại. Thử lại.",
    "playerNotFoundPin": "Không tìm thấy người chơi.",
    "wrongPin": "❌ Sai PIN. Thử lại.",
    "wrongRecovery": "❌ Sai từ khóa khôi phục.",
    "pinMust4": "PIN phải có 4 chữ số.",
    "subscribedPro": "✅ Đã đăng ký! Chào mừng đến Pro.",
    "purchaseCancelled": "Mua hàng đã bị hủy.",
    "billingAppOnly": "Thanh toán chỉ có trong ứng dụng.",
    "purchaseRestored": "✅ Đã khôi phục mua hàng!",
    "noActiveSubscription": "Không tìm thấy đăng ký đang hoạt động.",
    "couldNotRestore": "Không thể khôi phục mua hàng.",
    "daysRemaining": "ngày còn lại",
    "trialEndedSub": "🔒 Hết thời gian dùng thử",
    "subscribeToContInue": "Đăng ký để tiếp tục",
    "activeSubscription": "✅ Đang hoạt động",
    "subscribed": "Đã đăng ký",
    "noRegisteredPlayers": "Không tìm thấy người chơi đã đăng ký",
    "clearHistoryConfirm": "Xóa lịch sử?",
    "clearFavoritesConfirm": "Xóa yêu thích?",
    "helpUnavailable": "Trợ giúp không khả dụng. Kiểm tra kết nối.",
    "stillNeedHelp": "Vẫn cần giúp đỡ? Liên hệ hỗ trợ",
    "syncing": "🔄 Đang đồng bộ...",
    "noClubSelectedWarn": "⚠️ Chưa chọn CLB",
    "noPlayersFoundWarn": "⚠️ Không tìm thấy người chơi",
    "offlineCache": "⚠️ Ngoại tuyến -- dùng bộ nhớ đệm",
    "welcomeToApp": "Chào mừng đến Lịch Trình CLB Thể Thao",
    "connectClubToStart": "Kết nối CLB để bắt đầu.",
    "goToVault": "Đến Kho",
    "startGame": "Bắt đầu",
    "readyGame": "Sẵn sàng",
    "inProgressGame": "Đang diễn ra",
    "noneGame": "Không có",
    "emptyGame": "(Trống)",
    "releaseFromSession": "khỏi phiên đang hoạt động?",
    "releaseAllConfirm": "Giải phóng TẤT CẢ người chơi bị khóa?",
    "adminRole": "· Quản trị",
    "userRole": "· Người dùng",
    "leaveClubConfirm": "Rời CLB này?",
    "leaveVaultConfirm": "Rời CLB này? Bạn cần kết nối lại để truy cập Kho.",
    "awaitingApproval": "đang chờ admin phê duyệt. Kiểm tra lại sau.",
    "yourRequestToJoin": "Yêu cầu tham gia:",
    "notAvailable": "Không khả dụng",
    "creatingClub": "Đang tạo...",
    "creatingClubDot": "Đang tạo CLB...",
    "selectClubToDelete": "Chọn CLB để xóa.",
    "verifyingDot": "Đang xác minh...",
    "clubNotFound": "Không tìm thấy CLB.",
    "wrongAdminPassword": "Sai mật khẩu quản trị.",
    "playerNicknamePh": "Biệt danh người chơi",
    "defaultPasswordPh": "ví dụ: club123",
    "enterDefaultPwAll": "Nhập mật khẩu mặc định cho tất cả người chơi.",
    "registeringDot": "Đang đăng ký...",
    "enterNickname": "Vui lòng nhập biệt danh.",
    "enterDefaultPw": "Vui lòng đặt mật khẩu mặc định.",
    "nicknameExists": "Biệt danh đã tồn tại trong CLB này.",
    "passwordsNotMatchDot": "Mật khẩu không khớp.",
    "justStarted": "vừa bắt đầu",
    "selectYourClub": "Chọn CLB của bạn",
    "enterYourNickname": "Nhập biệt danh của bạn",
    "enterDefaultPassword": "Nhập mật khẩu mặc định",
    "sendingVerification": "Đang gửi mã xác minh...",
    "claimFailed": "Xác nhận thất bại. Thử lại.",
    "invalidOTP": "OTP không hợp lệ",
    "otpExpired": "OTP đã hết hạn. Vui lòng yêu cầu mã mới.",
    "accountNotFound": "Không tìm thấy tài khoản",
    "pleaseLoginFirst": "Vui lòng đăng nhập trước",
    "invalidInviteCode": "Mã mời không hợp lệ. Kiểm tra với người tổ chức.",
    "failedToJoinClub": "Tham gia CLB thất bại.",
    "searchFailed2": "Tìm kiếm thất bại",
    "provideNickname": "Vui lòng cung cấp biệt danh.",
    "failedSendRequest": "Gửi yêu cầu thất bại",
    "failedLoadRequests2": "Tải yêu cầu thất bại",
    "failedAcceptRequest": "Chấp nhận yêu cầu thất bại",
    "failedRejectRequest": "Từ chối yêu cầu thất bại",
    "pleaseSelectClubDot": "Vui lòng chọn CLB.",
    "enterClubPassword": "Nhập mật khẩu CLB.",
    "checkingDot": "Đang kiểm tra...",
    "wrongPasswordDot": "Sai mật khẩu.",
    "joinedAsAdmin": "✅ Đã tham gia với tư cách Quản trị",
    "enterAdminPasswordPh": "Mật khẩu quản trị",
    "enterAdminPasswordHint": "Nhập mật khẩu quản trị",
    "checkingDotDot": "Đang kiểm tra...",
    "wrongAdminPw": "Sai mật khẩu quản trị",
    "endingSession": "⏹ Đang kết thúc phiên...",
    "sessionEnded": "✅ Phiên đã kết thúc",
    "clubCreatedAdmin": "đã được tạo! Bạn là quản trị viên.",
    "setPinTitle": "Đặt PIN (4 chữ số)",
    "confirmPin": "Xác nhận PIN",
    "recoveryWordSecret": "Từ khóa khôi phục (bí mật)",
    "enterPin": "Nhập PIN",
    "recoveryWord": "Từ khóa khôi phục",
    "newPin": "PIN mới (4 chữ số)",
    "confirmNewPin": "Xác nhận PIN mới",
    "alreadyPlayingSession": "Đã chơi trong phiên khác",
    "availableStatus": "Sẵn sàng",
    "searchToAddPlayer": "Tìm kiếm để thêm người chơi...",
    "tapToToggleGender": "Nhấn để đổi giới tính",
    "startingRating": "Xếp hạng ban đầu",
    "removeBtn": "Xóa",
    "alreadyExists": "đã tồn tại",
    "currentlyPlayingSession": "Hiện đang chơi trong phiên khác",
    "liveNowTitle": "Đang trực tiếp",
    "recentSessions": "Phiên gần đây",
    "noActiveSessions": "Không có phiên đang hoạt động",
    "noRecentSessions": "Không tìm thấy phiên gần đây",
    "playersCount": "người chơi",
    "roundsCount": "vòng",
    "setupProfileFirst": "Thiết lập hồ sơ của bạn trước.",
    "tapProfileIcon": "Nhấn vào biểu tượng hồ sơ để chọn tên.",
    "noClubSelectedDash": "Chưa chọn CLB.",
    "goToClubTab": "Vào tab CLB để tham gia.",
    "couldNotLoadSessions": "Không thể tải phiên.",
    "checkConnection": "Kiểm tra kết nối của bạn.",
    "retryBtn": "↺ Thử lại",
    "pendingPrefix": "⏳ Đang chờ: ",
    "deleteSetConfirm": "Xóa bộ",
    "noClubSelectedWarn2": "⚠️ Chưa chọn CLB.",
    "adminModeRequired": "⚠️ Yêu cầu chế độ quản trị.",
    "noPlayersYetVault": "CLB chưa có người chơi. Thêm người chơi trong Kho.",
    "clubPasswordPh": "Mật khẩu CLB",
    "clubNamePh": "Tên CLB",
    "memberPasswordPh": "Mật khẩu thành viên",
    "errorPrefix": "Lỗi: ",
    "playerPrefix": "Người chơi ",
    "sessionBadge": "PHIÊN",
    "vsLabel": "VS",
    "playersSelected": "đã chọn",
    "playersActive": "đang hoạt động",
    "pairSet": "cặp đã đặt",
    "pairsSet": "cặp đã đặt",
    "courtSingle": "sân",
    "courtPlural": "sân",
    "report": "Báo cáo",
    "monthlyStats": "thống kê tháng",
    "foundInClub": "tìm thấy trong",
    "enterDefaultPwClaim": "Nhập mật khẩu mặc định để tham gia:",
    "claimAndJoin": "Xác nhận & Tham gia",
    "historyBtn": "Lịch sử"
  },
  "zh": {
    "home": "首页",
    "players": "球员",
    "rounds": "回合",
    "summary": "汇总",
    "language": "语言",
    "fontSize": "字体大小",
    "reset": "重置",
    "resetAll": "重置应用",
    "resetExcept": "仅重置比赛",
    "enterCourts": "输入场地数量",
    "importPlayers": "浏览玩家 ▶",
    "gender": "性别",
    "male": "男",
    "female": "女",
    "import": "导入",
    "enterPlayerName": "输入球员姓名",
    "fixedPairs2": "设置固定搭档（可选）",
    "pround": " 回合",
    "nround": "开始回合 ",
    "endrounds": "结束并进入下一回合 ",
    "endSession": "结束会话",
    "roundno": "回合 ",
    "roundShort": "R",
    "rank": "排名",
    "name": "姓名",
    "wins": "胜利",
    "played": "已比赛",
    "rested": "休息次数",
    "importExample": "姓名,性别\nKari\nBhavani",
    "Timer": "计时器",
    "min": "分钟",
    "selectPlayer1": "选择球员 1",
    "selectPlayer2": "选择球员 2",
    "small": "小",
    "medium": "中",
    "large": "大",
    "maxcourts": "请输入场地数量",
    "sittingOut": "休息中:",
    "courts": "场地",
    "theme": "主题",
    "light": "浅色",
    "dark": "深色",
    "export": "导出",
    "exporthtml": "📄 导出汇总",
    "confirmResetAll": "确定要重置所有内容吗？",
    "confirmResetGames": "确定只重置比赛吗？",
    "endRoundsConfirm": "确定要结束回合吗？",
    "yes": "确定",
    "help": "帮助",
    "statusReady": "状态: 就绪",
    "statusProgress": "状态: 进行中...",
    "minRounds": "热身轮次",
    "roundSettings": "回合设置",
    "competitive": "竞技模式",
    "browsePlayersSub": "从已保存的球员中选择",
    "appTitle": "运动俱乐部调度器",
    "tagline": "羽毛球 & 匹克球",
    "login": "登录",
    "logout": "登出",
    "createAccount": "创建账户",
    "claimAccount": "认领账户",
    "email": "电子邮件",
    "password": "密码",
    "confirmPassword": "确认密码",
    "newPassword": "新密码",
    "confirmNewPassword": "确认新密码",
    "displayName": "显示名称",
    "recoveryKeyword": "恢复关键词",
    "forgotPassword": "忘记密码？",
    "resetPassword": "重置密码",
    "userId": "用户ID",
    "nickname": "昵称",
    "yourEmail": "您的邮箱",
    "myCard": "我的卡片",
    "myClubs": "我的俱乐部",
    "dashboard": "仪表板",
    "fixedPairs": "固定搭档",
    "selectPlayers": "选择球员",
    "startRounds": "开始回合",
    "watchSession": "观看场次",
    "viewer": "观看者",
    "organiser": "组织者",
    "vault": "管理库",
    "chooseMode": "选择模式",
    "howUsingApp": "选择您使用应用的方式",
    "watchLive": "观看实时回合与比分",
    "runSession": "管理场次、记录分数、管理球员",
    "clubAdmin": "俱乐部管理 -- 球员、请求、管理",
    "roundOrganiser": "回合组织者",
    "vaultManager": "管理库管理员",
    "myClubsTitle": "我的俱乐部",
    "findClub": "查找俱乐部",
    "joinClub": "加入",
    "leaveClub": "离开",
    "noClubSelected": "未选择俱乐部",
    "createClub": "创建俱乐部",
    "createNewClub": "创建新俱乐部",
    "createYourClub": "创建您的俱乐部",
    "deleteClub": "删除俱乐部",
    "connectClub": "连接",
    "clubManagement": "俱乐部管理",
    "noClubYet": "还没有俱乐部，创建一个开始吧",
    "searchClub": "搜索俱乐部",
    "findRequest": "查找 & 申请",
    "submitRequest": "提交申请",
    "requestSent": "申请已发送！等待管理员批准。",
    "tapConnect": "点击连接",
    "register": "注册",
    "modify": "修改",
    "requests": "请求",
    "playing": "比赛中",
    "onCourtNow": "正在比赛",
    "pendingApproval": "等待批准",
    "playersInClub": "俱乐部球员",
    "tapToEdit": "点击编辑",
    "joinAClub": "加入俱乐部",
    "newClub": "新俱乐部",
    "removeClub": "删除俱乐部",
    "loadingRequests": "加载请求中...",
    "addPlayer": "添加球员",
    "editPlayer": "编辑球员",
    "addRemove": "添加 · 删除",
    "alwaysTogether": "始终搭档",
    "addAtLeast4": "请至少添加4名球员",
    "myProfile": "我的资料",
    "recentMatches": "近期比赛",
    "sessionStats": "场次统计",
    "sessions": "场次",
    "allTimeWins": "历史总胜",
    "allTimeLosses": "历史总负",
    "globalRating": "全球评分",
    "globalPoints": "全球积分",
    "clubRating": "俱乐部评分",
    "clubPoints": "俱乐部积分",
    "thisWeek": "本周",
    "thisMonth": "本月",
    "thisYear": "今年",
    "signInStats": "登录以查看您的统计",
    "trackStats": "追踪您的评分、胜利和比赛历史。",
    "appearance": "外观",
    "tileStyle": "磁贴样式",
    "flat": "平面",
    "glow": "发光",
    "color": "彩色",
    "subscription": "订阅",
    "currentMode": "当前模式",
    "freeTrial": "🎉 免费试用",
    "restorePurchase": "恢复购买",
    "subscribeNow": "立即订阅",
    "trialEnded": "免费试用已结束",
    "add": "添加",
    "cancel": "取消",
    "save": "保存更改",
    "clear": "清除",
    "clearHistory": "清除历史",
    "clearFavorites": "清除收藏",
    "delete": "删除",
    "replace": "替换",
    "skip": "跳过",
    "start": "开始",
    "end": "结束",
    "switch": "切换",
    "change": "更改",
    "info": "信息",
    "preview": "预览",
    "loading": "加载中...",
    "liveSessions": "直播场次",
    "liveNow": "正在直播",
    "noLiveSessions": "没有直播场次",
    "favourite": "收藏",
    "history": "历史",
    "whoAreYou": "您是谁？",
    "notSelected": "未选择",
    "getStarted": "开始使用",
    "welcome": "欢迎",
    "selectFromSaved": "从已保存球员中选择",
    "selectNameProfile": "选择名字以个性化您的资料",
    "asRegisteredByAdmin": "管理员注册的名称",
    "givenByAdmin": "管理员提供",
    "minSixChars": "最少6个字符",
    "toResetPassword": "用于重置密码",
    "yourNameAlias": "您的姓名或别名",
    "defaultPassword": "默认密码",
    "tile": "磁贴",
    "wideTile": "宽磁贴",
    "description": "描述",
    "addPlayer2": "添加",
    "addPlayers": "添加球员",
    "adminAccess": "管理员访问",
    "adminBadge": "ADMIN",
    "backHome": "‹ 首页",
    "browseBtn": "浏览",
    "claimMyAccount": "申请账户",
    "clearBtn": "清除",
    "clubLabel": "俱乐部",
    "clubRatingLabel": "俱乐部评分",
    "clubSchedulerPro": "CLUB Scheduler Pro",
    "connectToClub": "连接俱乐部",
    "connectToClubBadminton": "🏸 连接俱乐部",
    "court": "场地",
    "courtsLabel": "场地",
    "editPlayerName": "编辑球员名称",
    "emailLabel": "电子邮件",
    "endBtn": "结束",
    "favouriteBtn": "收藏",
    "findAClub": "查找俱乐部",
    "findYourClub": "找到您的俱乐部",
    "globalRatingLabel": "全球评分",
    "goBtn": "开始 ›",
    "helpGuide": "帮助与指南",
    "howUsingAppToday": "今天您如何使用应用？",
    "inProgress": "进行中",
    "joinBtn": "加入",
    "joinRequests": "加入请求",
    "lessOneShuttle": "每年少于一个羽毛球",
    "liveBadge": "LIVE",
    "loadingClubs": "-- 正在加载俱乐部... --",
    "lockBtn": "锁定",
    "markAllWinners": "请为所有比赛标记获胜者",
    "markWinner": "标记获胜者",
    "modifyPlayers": "修改球员",
    "newBadge": "新",
    "nextRound": "下一回合",
    "pairsLabel": "搭档",
    "passwordBlank": "密码（不更改请留空）",
    "passwordLabel": "密码",
    "player1": "球员1",
    "player2": "球员2",
    "playingNow": "正在比赛",
    "readyBadge": "就绪",
    "refresh": "↻ 刷新",
    "registerPlayers": "注册球员",
    "removePlayer": "删除球员",
    "replaceBtn": "替换",
    "resendCode": "重新发送验证码",
    "resetRoundsOnly": "仅重置回合",
    "resting": "休息中",
    "round": "回合",
    "roundOrganiserDesc": "管理场次、记录分数、管理球员",
    "roundsLabel": "回合",
    "saveSet": "保存组合",
    "searchByClubName": "按俱乐部名称搜索并申请",
    "selectClub": "-- 选择俱乐部 --",
    "selectClubDelete": "-- 选择要删除的俱乐部 --",
    "selectClubOption": "-- 选择俱乐部 --",
    "sessionStatsLabel": "场次统计",
    "settings": "设置",
    "skipBtn": "跳过",
    "startBtn": "开始",
    "startRoundsBtn": "开始回合 ›",
    "subFeature1": "✓ 完整统计与场次历史",
    "subFeature2": "✓ 实时回合与计分",
    "subFeature3": "✓ 组织者模式 -- 管理场次",
    "subFeature4": "✓ 球员与固定搭档管理",
    "subFeature5": "✓ 观看者模式 -- 观看实时分数",
    "summaryLabel": "汇总",
    "switchBtn": "切换",
    "sync": "↻ 同步",
    "unlockBtn": "解锁",
    "useAdminMode": "使用Vault模式获得完整管理权限",
    "userBadge": "USER",
    "userID": "用户ID",
    "vaultManagerDesc": "俱乐部管理 -- 球员、请求、管理",
    "verifyEmail": "验证邮箱",
    "viewerBadge": "VIEWER",
    "watchLiveDesc": "观看实时回合与比分",
    "welcomeTitle": "欢迎",
    "notConnected": "未连接",
    "setupBadge": "SETUP",
    "memberMsg": "您是该俱乐部的成员。",
    "club": "俱乐部",
    "clubs": "俱乐部",
    "pending": "待处理",
    "loginToSeeClubs": "登录以查看俱乐部",
    "noClubsYetSearch": "还没有俱乐部。在下方搜索加入。",
    "noClubsYet": "还没有俱乐部。",
    "couldNotLoadClubs": "无法加载俱乐部。",
    "searching": "搜索中...",
    "noClubsFoundFor": "未找到俱乐部",
    "joined": "已加入",
    "welcomeBack": "欢迎回来",
    "requestPending": "请求待处理",
    "checking": "检查中...",
    "requestSentTitle": "请求已发送！",
    "waitingAdminApproval": "等待管理员批准。",
    "doneBtn": "完成 ✓",
    "setUpBtn": "设置 ›",
    "alreadyTaken": "已被使用",
    "chooseDifferentNickname": "请为此俱乐部选择不同的昵称",
    "noRoundsYet": "暂无回合",
    "joinClubToPlay": "加入俱乐部以查看正在比赛的球员。",
    "noPlayersLocked": "当前没有锁定的球员。",
    "failedLoadConnection": "加载失败。请检查连接。",
    "noPlayersInDb": "数据库中还没有球员。",
    "adminAccessRequired": "🔒 需要管理员权限。",
    "joinClubToManage": "加入俱乐部以管理球员。",
    "failedLoadPlayers": "球员加载失败。",
    "noPlayersMatch": "没有匹配的球员。",
    "noClubSelectedJoin": "⚠️ 未选择俱乐部。请先加入俱乐部。",
    "playerNotFound": "未找到球员。",
    "noPlayersAvailable": "没有可用的球员",
    "pleaseWait": "请稍候...",
    "selectClubTitle": "选择俱乐部",
    "searchFailed": "搜索失败。请重试。",
    "noClubsFound": "未找到俱乐部。请检查名称。",
    "sendingRequest": "正在发送请求...",
    "connectClubFirst": "请先连接俱乐部。",
    "noPendingRequests": "没有待处理的请求。",
    "failedLoadRequests": "加载请求失败。",
    "forceEndSession": "⏹ 强制结束场次",
    "ending": "结束中...",
    "typeClubSearch": "输入俱乐部名称搜索...",
    "playerSingular": "球员",
    "playerPlural": "球员",
    "releaseAll": "🔓 全部释放",
    "badgeActive": "活跃",
    "badgeMember": "成员",
    "badgePending": "待处理",
    "asNick": "作为",
    "requestPendingText": "请求待处理",
    "winsShort": "胜",
    "lossesShort": "负",
    "sessionActive": "场次已开始！",
    "registeredBadge": "✅ 已注册",
    "noAccountBadge": "无账户",
    "genderMale": "男",
    "genderFemale": "女",
    "genderAll": "全部",
    "searchPlayers": "搜索球员...",
    "searchPlayerDot": "搜索球员...",
    "searchHelp": "搜索帮助...",
    "noResultsFound": "未找到结果",
    "adminBadgeFull": "🔑 管理员",
    "userBadgeFull": "👤 用户",
    "changePassword": "🔑 更改密码",
    "wrongPassword": "密码错误。请重试。",
    "passwordMin4": "密码至少需要4个字符。",
    "passwordsNotMatch": "密码不匹配",
    "passwordMin6": "密码至少需要6个字符",
    "memberAdminDiff": "成员密码和管理员密码必须不同。",
    "emailRequired": "邮箱是必填项",
    "emailInvalid": "请输入有效的邮箱地址",
    "displayNameMin2": "显示名称至少需要2个字符",
    "recoveryMin3": "恢复关键词至少需要3个字符",
    "emailAlreadyReg": "该邮箱已注册。请登录。",
    "signupFailed": "注册失败。请重试。",
    "enterEmail": "请输入邮箱",
    "enterPassword": "请输入密码",
    "noAccountEmail": "未找到该邮箱的账户",
    "wrongPasswordLogin": "密码错误",
    "loginFailed": "登录失败。请重试。",
    "enterRecovery": "请输入恢复关键词",
    "emailRecoveryWrong": "邮箱或恢复关键词不正确",
    "resetFailed": "重置失败。请重试。",
    "nicknameNotFound": "在此俱乐部未找到昵称。请与管理员确认。",
    "alreadyClaimed": "此账户已被申请。请登录或重置密码。",
    "defaultPwWrong": "默认密码不正确。请与管理员确认。",
    "emailAlreadyUsed": "此邮箱已注册。请使用不同的邮箱。",
    "nameCannotBeEmpty": "名称不能为空。",
    "saving": "保存中...",
    "saved": "✅ 已保存！",
    "enterClubName": "请输入俱乐部名称。",
    "enterMemberPw": "请输入成员密码。",
    "enterAdminPw": "请输入管理员密码。",
    "selectPlayersStep": "选择球员",
    "addAtLeast4Step": "至少添加4名球员才能开始",
    "fixedPairsStep": "固定搭档",
    "fixedPairsOptional": "可选 -- 配对总是一起打的球员",
    "skippedOptional": "已跳过（可选）",
    "courtSettings": "场地设置",
    "setCourtMode": "设置场地和比赛模式",
    "randomMode": "随机",
    "startRoundsStep": "开始回合",
    "allSetReady": "准备就绪 -- 开始比赛！",
    "sessionInProgress": "场次进行中",
    "optional": "可选",
    "liveSession": "直播场次",
    "youMemberMultipleClubs": "您是多个俱乐部的成员",
    "requestToJoin": "申请加入 ›",
    "accept": "✓ 接受",
    "reject": "✗ 拒绝",
    "verifyEmailTitle": "验证邮箱",
    "enterSixDigit": "输入发送到邮箱的6位验证码",
    "verifyBtn": "验证",
    "enterSixDigitHint": "输入6位验证码",
    "codeResent": "✅ 验证码已重新发送",
    "passwordReset": "✅ 密码已重置！请登录。",
    "noClubsFoundDot": "未找到俱乐部。",
    "couldNotLoadClubsErr": "❌ 无法加载俱乐部:",
    "pleaseSelectClub": "请选择俱乐部。",
    "enterPasswordHint": "请输入密码。",
    "enterMemberPwHint": "请输入成员密码。",
    "wrongPasswordHint": "密码错误。",
    "joinedSuccessfully": "✅ 加入成功",
    "connectedAsMember": "✅ 已作为成员连接",
    "noSessionData": "暂无场次数据。<br>请先完成一些回合。",
    "noSessionDataAvail": "没有可用的场次数据。",
    "couldNotLoadSession": "无法加载场次数据。",
    "today": "今天",
    "yesterday": "昨天",
    "forceEndConfirm": "强制结束此场次？此操作无法撤销。",
    "rookie": "新手",
    "clubLevel": "俱乐部",
    "competitiveLevel": "竞技",
    "advancedLevel": "高级",
    "eliteLevel": "精英",
    "notSelectedProfile": "未选择",
    "loadingPlayers": "正在加载球员...",
    "noPlayersInClub": "在俱乐部中未找到球员。",
    "pinMustBe4": "PIN必须正好是4位数字。",
    "pinsNotMatch": "PIN不匹配。",
    "recoveryTooShort": "恢复关键词太短。",
    "savingPin": "⏳ 保存中...",
    "failedSave": "保存失败。请重试。",
    "playerNotFoundPin": "未找到球员。",
    "wrongPin": "❌ PIN错误。请重试。",
    "wrongRecovery": "❌ 恢复关键词错误。",
    "pinMust4": "PIN必须是4位数字。",
    "subscribedPro": "✅ 已订阅！欢迎加入Pro。",
    "purchaseCancelled": "购买已取消。",
    "billingAppOnly": "仅在应用内可进行计费。",
    "purchaseRestored": "✅ 购买已恢复！",
    "noActiveSubscription": "未找到有效订阅。",
    "couldNotRestore": "无法恢复购买。",
    "daysRemaining": "天剩余",
    "trialEndedSub": "🔒 试用结束",
    "subscribeToContInue": "订阅以继续",
    "activeSubscription": "✅ 活跃",
    "subscribed": "已订阅",
    "noRegisteredPlayers": "未找到已注册球员",
    "clearHistoryConfirm": "清除历史？",
    "clearFavoritesConfirm": "清除收藏？",
    "helpUnavailable": "帮助不可用。请检查连接。",
    "stillNeedHelp": "仍需帮助？联系支持",
    "syncing": "🔄 同步中...",
    "noClubSelectedWarn": "⚠️ 未选择俱乐部",
    "noPlayersFoundWarn": "⚠️ 未找到球员",
    "offlineCache": "⚠️ 离线 -- 使用缓存",
    "welcomeToApp": "欢迎使用运动俱乐部调度器",
    "connectClubToStart": "连接您的俱乐部以开始。",
    "goToVault": "前往管理库",
    "startGame": "开始",
    "readyGame": "就绪",
    "inProgressGame": "进行中",
    "noneGame": "无",
    "emptyGame": "(空)",
    "releaseFromSession": "从活跃场次中？",
    "releaseAllConfirm": "释放所有锁定球员？",
    "adminRole": "· 管理员",
    "userRole": "· 用户",
    "leaveClubConfirm": "离开此俱乐部？",
    "leaveVaultConfirm": "离开此俱乐部？您需要重新连接才能访问管理库。",
    "awaitingApproval": "正在等待管理员批准。请稍后检查。",
    "yourRequestToJoin": "加入请求：",
    "notAvailable": "不可用",
    "creatingClub": "创建中...",
    "creatingClubDot": "正在创建俱乐部...",
    "selectClubToDelete": "选择要删除的俱乐部。",
    "verifyingDot": "验证中...",
    "clubNotFound": "未找到俱乐部。",
    "wrongAdminPassword": "管理员密码错误。",
    "playerNicknamePh": "球员昵称",
    "defaultPasswordPh": "例：club123",
    "enterDefaultPwAll": "请为所有球员输入默认密码。",
    "registeringDot": "注册中...",
    "enterNickname": "请输入昵称。",
    "enterDefaultPw": "请设置默认密码。",
    "nicknameExists": "此俱乐部中昵称已存在。",
    "passwordsNotMatchDot": "密码不匹配。",
    "justStarted": "刚刚开始",
    "selectYourClub": "选择您的俱乐部",
    "enterYourNickname": "输入您的昵称",
    "enterDefaultPassword": "输入默认密码",
    "sendingVerification": "正在发送验证码...",
    "claimFailed": "申请失败。请重试。",
    "invalidOTP": "无效的OTP",
    "otpExpired": "OTP已过期。请重新申请。",
    "accountNotFound": "未找到账户",
    "pleaseLoginFirst": "请先登录",
    "invalidInviteCode": "无效的邀请码。请与组织者确认。",
    "failedToJoinClub": "加入俱乐部失败。",
    "searchFailed2": "搜索失败",
    "provideNickname": "请提供昵称。",
    "failedSendRequest": "发送请求失败",
    "failedLoadRequests2": "加载请求失败",
    "failedAcceptRequest": "接受请求失败",
    "failedRejectRequest": "拒绝请求失败",
    "pleaseSelectClubDot": "请选择俱乐部。",
    "enterClubPassword": "输入俱乐部密码。",
    "checkingDot": "检查中...",
    "wrongPasswordDot": "密码错误。",
    "joinedAsAdmin": "✅ 已作为管理员加入",
    "enterAdminPasswordPh": "管理员密码",
    "enterAdminPasswordHint": "输入管理员密码",
    "checkingDotDot": "检查中...",
    "wrongAdminPw": "管理员密码错误",
    "endingSession": "⏹ 场次结束中...",
    "sessionEnded": "✅ 场次已结束",
    "clubCreatedAdmin": "已创建！您现在是管理员。",
    "setPinTitle": "设置PIN（4位数字）",
    "confirmPin": "确认PIN",
    "recoveryWordSecret": "恢复关键词（秘密）",
    "enterPin": "输入PIN",
    "recoveryWord": "恢复关键词",
    "newPin": "新PIN（4位数字）",
    "confirmNewPin": "确认新PIN",
    "alreadyPlayingSession": "已在其他场次中比赛",
    "availableStatus": "可用",
    "searchToAddPlayer": "搜索添加球员...",
    "tapToToggleGender": "点击切换性别",
    "startingRating": "初始评分",
    "removeBtn": "删除",
    "alreadyExists": "已存在",
    "currentlyPlayingSession": "当前正在其他场次中比赛",
    "liveNowTitle": "正在直播",
    "recentSessions": "近期场次",
    "noActiveSessions": "当前没有活跃场次",
    "noRecentSessions": "未找到近期场次",
    "playersCount": "球员",
    "roundsCount": "回合",
    "setupProfileFirst": "请先设置您的个人资料。",
    "tapProfileIcon": "点击个人资料图标选择您的名字。",
    "noClubSelectedDash": "未选择俱乐部。",
    "goToClubTab": "前往俱乐部标签页加入俱乐部。",
    "couldNotLoadSessions": "无法加载场次。",
    "checkConnection": "请检查您的连接。",
    "retryBtn": "↺ 重试",
    "pendingPrefix": "⏳ 待处理: ",
    "deleteSetConfirm": "删除组合",
    "noClubSelectedWarn2": "⚠️ 未选择俱乐部。",
    "adminModeRequired": "⚠️ 需要管理员模式。",
    "noPlayersYetVault": "俱乐部还没有球员。请在管理库中添加球员。",
    "clubPasswordPh": "俱乐部密码",
    "clubNamePh": "俱乐部名称",
    "memberPasswordPh": "成员密码",
    "errorPrefix": "错误: ",
    "playerPrefix": "球员 ",
    "sessionBadge": "场次",
    "vsLabel": "VS",
    "playersSelected": "已选择",
    "playersActive": "活跃",
    "pairSet": "搭档已设置",
    "pairsSet": "搭档已设置",
    "courtSingle": "场地",
    "courtPlural": "场地",
    "report": "报告",
    "monthlyStats": "月度统计",
    "foundInClub": "在俱乐部中找到:",
    "enterDefaultPwClaim": "输入默认密码加入:",
    "claimAndJoin": "认领并加入",
    "historyBtn": "历史"
  }
};
