/* ============================================================
   I18N — All UI translations EN/JP/KR/VI/ZH
   File: engjap.js
   ============================================================ */

const translations = {
  en: {
    appTitle: "CLUB Scheduler",
    home: "Home",
    language: "Language",
    settings: "Settings",
    players: "Players",
    rounds: "Rounds",
    summary: "Summary",
    fontSize: "Font Size",
    reset: "Reset",
    resetAll: "Reset App",
    resetExcept: "Reset Games",
    enterCourts: "Enter Number of Courts",
    importPlayers: "Browse Players ▶",
    gender: "Gender",
    male: "Male",
    female: "Female",
    import: "Import",
    cancel: "Cancel",
    enterPlayerName: "Enter Player Name",
    addPlayer: "Add",
    fixedPairs: "Set Fixed Pairs (Optional)",
    add: "Add",
    pround: " Round",
    nround: "Play ",
    endrounds: "Finish & Next Round ",
    endSession: "End Session",
    roundno: "Round ",
    roundShort: "R",
    rank: "Rank",
    name: "Name",
    wins: "Wins",
    played: "Played",
    rested: "Rested",
    importExample: "Name,Gender\nKari\nBhavani",
    Timer: "Timer",
    min: "min",
    selectPlayer1: "Select Player 1",
    selectPlayer2: "Select Player 2",
    small: "Small",
    medium: "Medium",
    large: "Large",
    maxcourts: "Enter Number of Courts",
    sittingOut: "Resting",
    courts: "Courts",
    theme: "Theme",
    light: "Light",
    dark: "Dark",
    export: "Export",
    exporthtml: "📄 Export Summary",
    help: "Help",
    confirmResetAll: "Do you want to reset everything?",
    confirmResetGames: "Do you want to reset games only?",
    endRoundsConfirm: "Do you want to end the rounds?",
    yes: "Yes",
    browsePlayersSub: "Select from saved players",
    statusReady: "Status: Ready",
    statusProgress: "Status: Progress…",
    minRounds: "Warm-Up Rounds",
    roundSettings: "Round Settings",
    competitive: "Competitive"
  },

  jp: {
    appTitle: "CLUB Scheduler",
    home: "ホーム",
    players: "選手一覧",
    rounds: "試合ラウンド",
    summary: "集計",
    language: "言語",
    fontSize: "文字サイズ",
    reset: "リセット",
    resetAll: "全てをリセット",
    resetExcept: "プレーヤー以外をリセット",
    enterCourts: "コート数を入力",
    importPlayers: "プレイヤーを閲覧 ▶",
    gender: "性別",
    male: "男",
    female: "女",
    import: "取り込み",
    cancel: "キャンセル",
    enterPlayerName: "選手名を入力",
    addPlayer: "追加",
    fixedPairs: "固定ペア設定（任意）",
    add: "追加",
    pround: " ラウンド",
    nround: "ラウンド開始 ",
    endrounds: "終了して次のラウンド ",
    endSession: "セッション終了",
    roundno: "ラウンド ",
    roundShort: "R",
    rank: "順位",
    name: "名前",
    wins: "勝利",
    played: "試合数",
    rested: "休憩数",
    importExample: "名前,性別\nカリ\nババニ",
    Timer: "タイマー",
    min: "分",
    selectPlayer1: "プレーヤー1を選択",
    selectPlayer2: "プレーヤー2を選択",
    small: "小",
    medium: "中",
    large: "大",
    maxcourts: "コートの数を入力してください",
    sittingOut: "休憩中:",
    courts: "コート",
    theme: "テーマ",
    light: "ライト",
    dark: "ダーク",
    export: "エクスポート",
    exporthtml: "📄 概要出力",
    confirmResetAll: "すべてをリセットしますか？",
    confirmResetGames: "試合のみをリセットしますか？",
    endRoundsConfirm: "ラウンドを終了しますか？",
    yes: "はい",
    help: "ヘルプ",
    statusReady: "状態: 準備完了",
    statusProgress: "状態: 進行中...",
    minRounds: "ウォームアップラウンド",
    roundSettings: "ラウンド設定",
    competitive: "競技モード",
    browsePlayersSub: "保存済みプレイヤーから選択"
  },

  kr: {
    appTitle: "CLUB Scheduler",
    home: "홈",
    players: "선수",
    rounds: "라운드",
    summary: "요약",
    language: "언어",
    fontSize: "글자 크기",
    reset: "초기화",
    resetAll: "전체 초기화",
    resetExcept: "경기만 초기화",
    enterCourts: "코트 수 입력",
    importPlayers: "플레이어 찾아보기 ▶",
    gender: "성별",
    male: "남성",
    female: "여성",
    import: "가져오기",
    cancel: "취소",
    enterPlayerName: "선수 이름 입력",
    addPlayer: "선수 추가",
    fixedPairs: "고정 페어 설정 (선택)",
    add: "추가",
    pround: " 라운드",
    nround: "라운드 시작 ",
    endrounds: "종료 및 다음 라운드 ",
    endSession: "세션 종료",
    roundno: "라운드 ",
    roundShort: "R",
    rank: "순위",
    name: "이름",
    wins: "승리",
    played: "경기 수",
    rested: "휴식 수",
    importExample: "이름,성별\n카리\n바바니",
    Timer: "타이머",
    min: "분",
    selectPlayer1: "선수 1 선택",
    selectPlayer2: "선수 2 선택",
    small: "작게",
    medium: "보통",
    large: "크게",
    maxcourts: "코트 수를 입력하세요",
    sittingOut: "휴식 중:",
    courts: "코트",
    theme: "테마",
    light: "라이트",
    dark: "다크",
    export: "내보내기",
    exporthtml: "📄 요약 내보내기",
    confirmResetAll: "모든 데이터를 초기화하시겠습니까?",
    confirmResetGames: "경기만 초기화하시겠습니까?",
    endRoundsConfirm: "라운드를 종료하시겠습니까?",
    yes: "확인",
    help: "도움말",
    statusReady: "상태: 준비 완료",
    statusProgress: "상태: 진행 중…",
    minRounds: "워밍업 라운드",
    roundSettings: "라운드 설정",
    competitive: "경쟁 모드",
    browsePlayersSub: "저장된 선수에서 선택"
  },

  vi: {
    appTitle: "CLUB Scheduler",
    home: "Trang chủ",
    players: "Người chơi",
    rounds: "Vòng đấu",
    summary: "Tóm tắt",
    language: "Ngôn ngữ",
    fontSize: "Cỡ chữ",
    reset: "Đặt lại",
    resetAll: "Đặt lại tất cả",
    resetExcept: "Đặt lại trận đấu",
    enterCourts: "Nhập số sân",
    importPlayers: "Duyệt người chơi ▶",
    gender: "Giới tính",
    male: "Nam",
    female: "Nữ",
    import: "Nhập",
    cancel: "Hủy",
    enterPlayerName: "Nhập tên người chơi",
    addPlayer: "Thêm người chơi",
    fixedPairs: "Cố định cặp đấu (Tùy chọn)",
    add: "Thêm",
    pround: " Vòng",
    nround: "Bắt đầu vòng ",
    endrounds: "Kết thúc & Vòng tiếp theo ",
    endSession: "Kết thúc phiên",
    roundno: "Vòng ",
    roundShort: "R",
    rank: "Xếp hạng",
    name: "Tên",
    wins: "Chiến thắng",
    played: "Số trận",
    rested: "Số lần nghỉ",
    importExample: "Tên,Giới tính\nKari\nBhavani",
    Timer: "Hẹn giờ",
    min: "phút",
    selectPlayer1: "Chọn người chơi 1",
    selectPlayer2: "Chọn người chơi 2",
    small: "Nhỏ",
    medium: "Vừa",
    large: "Lớn",
    maxcourts: "Nhập số sân",
    sittingOut: "Đang nghỉ:",
    courts: "Sân",
    theme: "Chủ đề",
    light: "Sáng",
    dark: "Tối",
    export: "Xuất",
    exporthtml: "📄 Xuất bản tóm tắt",
    confirmResetAll: "Bạn có muốn đặt lại tất cả không?",
    confirmResetGames: "Bạn có muốn đặt lại trận đấu không?",
    endRoundsConfirm: "Bạn có muốn kết thúc các vòng không?",
    yes: "Có",
    help: "Trợ giúp",
    statusReady: "Trạng thái: Sẵn sàng",
    statusProgress: "Trạng thái: Đang tiến hành…",
    minRounds: "Vòng khởi động",
    roundSettings: "Cài đặt vòng",
    competitive: "Cạnh tranh",
    browsePlayersSub: "Chọn từ danh sách đã lưu"
  },

  zh: {
    appTitle: "CLUB 调度器",
    home: "首页",
    players: "球员",
    rounds: "回合",
    summary: "汇总",
    language: "语言",
    fontSize: "字体大小",
    reset: "重置",
    resetAll: "重置应用",
    resetExcept: "仅重置比赛",
    enterCourts: "输入场地数量",
    importPlayers: "浏览玩家 ▶",
    gender: "性别",
    male: "男",
    female: "女",
    import: "导入",
    cancel: "取消",
    enterPlayerName: "输入球员姓名",
    addPlayer: "添加球员",
    fixedPairs: "设置固定搭档（可选）",
    add: "添加",
    pround: " 回合",
    nround: "开始回合 ",
    endrounds: "结束并进入下一回合 ",
    endSession: "结束会话",
    roundno: "回合 ",
    roundShort: "R",
    rank: "排名",
    name: "姓名",
    wins: "胜利",
    played: "已比赛",
    rested: "休息次数",
    importExample: "姓名,性别\nKari\nBhavani",
    Timer: "计时器",
    min: "分钟",
    selectPlayer1: "选择球员 1",
    selectPlayer2: "选择球员 2",
    small: "小",
    medium: "中",
    large: "大",
    maxcourts: "请输入场地数量",
    sittingOut: "休息中:",
    courts: "场地",
    theme: "主题",
    light: "浅色",
    dark: "深色",
    export: "导出",
    exporthtml: "📄 导出汇总",
    confirmResetAll: "确定要重置所有内容吗？",
    confirmResetGames: "确定只重置比赛吗？",
    endRoundsConfirm: "确定要结束回合吗？",
    yes: "确定",
    help: "帮助",
    statusReady: "状态: 就绪",
    statusProgress: "状态: 进行中…",
    minRounds: "热身轮次",
    roundSettings: "回合设置",
    competitive: "竞技模式",
    browsePlayersSub: "从已保存的球员中选择"
  }
};
